// Command gen-handset-font converts a BDF or TrueType/OpenType font into the
// compressed, base64-encoded handset glyph payload embedded by package runtime
// (see runtime/handset_font.go for the format and runtime/hangul_bitmap.go for
// the reference NeoDunggeunmo payload).
//
// The heavy lifting lives in runtime.BuildHandsetPack, which is shared with the
// runtime path that loads user-supplied fonts, so the embedded and runtime
// fonts are byte-for-byte identical for the same source.
//
// Usage:
//
//	go run ./internal/cmd/gen-handset-font \
//	    -in Galmuri9.bdf -var galmuri9 -source "Galmuri9" \
//	    -out runtime/galmuri9_bitmap.go
package main

import (
	"bytes"
	"compress/zlib"
	"encoding/base64"
	"flag"
	"fmt"
	"os"

	"github.com/mirusu400/aram-core/runtime"
)

func main() {
	inPath := flag.String("in", "", "input BDF or TrueType/OpenType font path")
	varName := flag.String("var", "", "Go identifier prefix, e.g. galmuri9")
	source := flag.String("source", "", "human font name for the header comment")
	outPath := flag.String("out", "", "output Go file path")
	flag.Parse()
	if *inPath == "" || *varName == "" || *outPath == "" {
		fmt.Fprintln(os.Stderr, "gen-handset-font: -in, -var and -out are required")
		os.Exit(2)
	}
	if *source == "" {
		*source = *varName
	}

	data, err := os.ReadFile(*inPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-handset-font: read %s: %v\n", *inPath, err)
		os.Exit(1)
	}
	payload, extraCount, err := runtime.BuildHandsetPack(data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-handset-font: build pack: %v\n", err)
		os.Exit(1)
	}

	var compressed bytes.Buffer
	zw, _ := zlib.NewWriterLevel(&compressed, zlib.BestCompression)
	if _, err := zw.Write(payload); err != nil {
		fmt.Fprintf(os.Stderr, "gen-handset-font: compress: %v\n", err)
		os.Exit(1)
	}
	if err := zw.Close(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-handset-font: compress close: %v\n", err)
		os.Exit(1)
	}
	encoded := base64.StdEncoding.EncodeToString(compressed.Bytes())

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by internal/cmd/gen-handset-font from %s. DO NOT EDIT.\n", *source)
	fmt.Fprintf(&out, "// 12x12 %s glyph data (Hangul syllables plus a curated non-Hangul\n", *source)
	fmt.Fprintf(&out, "// repertoire). The payload uses a neutral ARAM handset name; see\n")
	fmt.Fprintf(&out, "// THIRD_PARTY_NOTICES.md and third_party/ for the upstream font license\n")
	fmt.Fprintf(&out, "// and attribution.\n")
	fmt.Fprintf(&out, "package runtime\n\n")
	fmt.Fprintf(&out, "const %sExtraGlyphCount = %d\n\n", *varName, extraCount)
	fmt.Fprintf(&out, "const %sBitmapDataBase64 = `%s`\n", *varName, encoded)

	if err := os.WriteFile(*outPath, out.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-handset-font: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}

	fmt.Printf("gen-handset-font: %s -> %s (hangul block + %d extra, %d payload bytes, %d base64 bytes)\n",
		*source, *outPath, extraCount, len(payload), len(encoded))
}
