package main

import (
	"crypto/sha256"
	"encoding/csv"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type apiRow struct {
	ordinal    int
	family     string
	name       string
	slot       uint32
	prototype  string
	kind       string
	confidence string
	state      string
}

func main() {
	input := flag.String("input", "", "wipi_public_syscall_c_map.csv")
	output := flag.String("output", "wipi/catalog_gen.go", "generated Go output")
	flag.Parse()
	if strings.TrimSpace(*input) == "" {
		fatalf("-input is required")
	}

	source, err := os.ReadFile(*input)
	if err != nil {
		fatalf("read %s: %v", *input, err)
	}
	rows, err := readRows(strings.NewReader(string(source)))
	if err != nil {
		fatalf("parse %s: %v", *input, err)
	}
	generated, err := render(rows, sha256.Sum256(source), filepath.Base(*input))
	if err != nil {
		fatalf("render catalog: %v", err)
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fatalf("write %s: %v", *output, err)
	}
}

func readRows(input io.Reader) ([]apiRow, error) {
	reader := csv.NewReader(input)
	records, err := reader.ReadAll()
	if err != nil {
		return nil, err
	}
	if len(records) < 2 {
		return nil, fmt.Errorf("CSV contains no API rows")
	}
	header := make(map[string]int, len(records[0]))
	for index, name := range records[0] {
		header[name] = index
	}
	required := []string{
		"ordinal",
		"family",
		"api",
		"slot",
		"c_prototype",
		"selector_kind",
		"selector_confidence",
		"selector_state",
	}
	for _, name := range required {
		if _, ok := header[name]; !ok {
			return nil, fmt.Errorf("required column %q is missing", name)
		}
	}

	rows := make([]apiRow, 0, len(records)-1)
	for recordIndex, record := range records[1:] {
		value := func(name string) string {
			index := header[name]
			if index >= len(record) {
				return ""
			}
			return strings.TrimSpace(record[index])
		}
		ordinal, err := strconv.Atoi(value("ordinal"))
		if err != nil {
			return nil, fmt.Errorf("row %d ordinal: %w", recordIndex+2, err)
		}
		slotText := strings.TrimPrefix(value("slot"), "+")
		slot, err := strconv.ParseUint(strings.TrimPrefix(slotText, "0x"), 16, 32)
		if err != nil {
			return nil, fmt.Errorf("row %d slot %q: %w", recordIndex+2, value("slot"), err)
		}
		rows = append(rows, apiRow{
			ordinal:    ordinal,
			family:     value("family"),
			name:       value("api"),
			slot:       uint32(slot),
			prototype:  value("c_prototype"),
			kind:       value("selector_kind"),
			confidence: value("selector_confidence"),
			state:      value("selector_state"),
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].ordinal < rows[j].ordinal })
	if err := validate(rows); err != nil {
		return nil, err
	}
	return rows, nil
}

func validate(rows []apiRow) error {
	if len(rows) == 0 {
		return fmt.Errorf("catalog is empty")
	}
	names := make(map[string]struct{}, len(rows))
	slots := make(map[string]struct{}, len(rows))
	for index, row := range rows {
		if row.ordinal != index+1 {
			return fmt.Errorf("ordinal %d appears at position %d", row.ordinal, index+1)
		}
		if row.family == "" || row.name == "" || row.prototype == "" {
			return fmt.Errorf("ordinal %d has an empty required field", row.ordinal)
		}
		if row.slot&3 != 0 || row.slot >= PackageTableStride {
			return fmt.Errorf("ordinal %d has invalid slot 0x%x", row.ordinal, row.slot)
		}
		if _, exists := names[row.name]; exists {
			return fmt.Errorf("duplicate API name %q", row.name)
		}
		names[row.name] = struct{}{}
		key := fmt.Sprintf("%s:%x", row.family, row.slot)
		if _, exists := slots[key]; exists {
			return fmt.Errorf("duplicate selector %s", key)
		}
		slots[key] = struct{}{}
	}
	return nil
}

func render(rows []apiRow, digest [sha256.Size]byte, sourceName string) ([]byte, error) {
	var output strings.Builder
	fmt.Fprintln(&output, "// Code generated by internal/cmd/gen-wipi-catalog; DO NOT EDIT.")
	fmt.Fprintf(&output, "// Source: %s (SHA-256 %x).\n\n", sourceName, digest)
	fmt.Fprintln(&output, "package wipi")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "const CatalogSourceSHA256 = %q\n\n", fmt.Sprintf("%x", digest))
	fmt.Fprintln(&output, "var generatedAPIs = [...]API{")
	for _, row := range rows {
		fmt.Fprintf(
			&output,
			"\t{Ordinal: %d, Family: %s, Name: %s, Slot: 0x%02x, Prototype: %s, SelectorKind: %s, Confidence: %s, SelectorState: %s},\n",
			row.ordinal,
			strconv.Quote(row.family),
			strconv.Quote(row.name),
			row.slot,
			strconv.Quote(row.prototype),
			strconv.Quote(row.kind),
			strconv.Quote(row.confidence),
			strconv.Quote(row.state),
		)
	}
	fmt.Fprintln(&output, "}")
	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", arguments...)
	os.Exit(1)
}

const PackageTableStride = uint32(0x100)
