package ktf

var HostJavaClassSpecs = map[string]ktfHostJavaClassSpec{
	"java/lang/Object": {
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "getClass", descriptor: "()Ljava/lang/Class;"},
			{name: "hashCode", descriptor: "()I"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "clone", descriptor: "()Ljava/lang/Object;", access: 0x0100},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "notify", descriptor: "()V"},
			{name: "notifyAll", descriptor: "()V"},
			{name: "wait", descriptor: "(J)V"},
			{name: "wait", descriptor: "(JI)V"},
			{name: "wait", descriptor: "()V"},
			{name: "finalize", descriptor: "()V"},
		},
	},
	"java/lang/Class": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "getName", descriptor: "()Ljava/lang/String;"},
			{
				name:       "isAssignableFrom",
				descriptor: "(Ljava/lang/Class;)Z",
			},
			{
				name:       "getResourceAsStream",
				descriptor: "(Ljava/lang/String;)Ljava/io/InputStream;",
			},
			{
				name:       "forName",
				descriptor: "(Ljava/lang/String;)Ljava/lang/Class;",
				access:     0x0108,
			},
		},
	},
	"java/lang/String": {
		Parent:    "java/lang/Object",
		fieldSize: 12,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
			{name: "<init>", descriptor: "([B)V"},
			{name: "<init>", descriptor: "([BII)V"},
			{name: "<init>", descriptor: "([C)V"},
			{name: "<init>", descriptor: "([CII)V"},
			{name: "length", descriptor: "()I"},
			{name: "charAt", descriptor: "(I)C"},
			{name: "substring", descriptor: "(I)Ljava/lang/String;"},
			{name: "substring", descriptor: "(II)Ljava/lang/String;"},
			{name: "trim", descriptor: "()Ljava/lang/String;"},
			{name: "getBytes", descriptor: "()[B"},
			{name: "toCharArray", descriptor: "()[C"},
			{
				name:       "equals",
				descriptor: "(Ljava/lang/Object;)Z",
			},
			{
				name:       "concat",
				descriptor: "(Ljava/lang/String;)Ljava/lang/String;",
			},
			{
				name:       "startsWith",
				descriptor: "(Ljava/lang/String;)Z",
			},
			{
				name:       "endsWith",
				descriptor: "(Ljava/lang/String;)Z",
			},
			{name: "indexOf", descriptor: "(I)I"},
			{name: "indexOf", descriptor: "(II)I"},
			{
				name:       "indexOf",
				descriptor: "(Ljava/lang/String;)I",
			},
			{
				name:       "indexOf",
				descriptor: "(Ljava/lang/String;I)I",
			},
			{
				name:       "toLowerCase",
				descriptor: "()Ljava/lang/String;",
			},
			{
				name:       "toUpperCase",
				descriptor: "()Ljava/lang/String;",
			},
			{
				name:       "valueOf",
				descriptor: "(I)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(J)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(Z)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(C)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(Ljava/lang/Object;)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "([C)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "([CII)Ljava/lang/String;",
				access:     0x0008,
			},
		},
	},
	"java/lang/StringBuffer": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
			{
				name:       "append",
				descriptor: "(Ljava/lang/String;)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(Ljava/lang/Object;)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(Z)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(I)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(J)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(C)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "([CII)Ljava/lang/StringBuffer;",
			},
			{
				name:       "delete",
				descriptor: "(II)Ljava/lang/StringBuffer;",
			},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "setLength", descriptor: "(I)V"},
			{name: "length", descriptor: "()I"},
			{name: "charAt", descriptor: "(I)C"},
		},
	},
	"java/io/InputStream": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "available", descriptor: "()I"},
			{name: "read", descriptor: "([BII)I"},
			{name: "read", descriptor: "([B)I"},
			{name: "read", descriptor: "()I"},
			{name: "close", descriptor: "()V"},
			{name: "skip", descriptor: "(J)J"},
			{name: "mark", descriptor: "(I)V"},
			{name: "reset", descriptor: "()V"},
		},
	},
	"java/io/ByteArrayInputStream": {
		Parent: "java/io/InputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "([B)V"},
			{name: "<init>", descriptor: "([BII)V"},
		},
	},
	"java/io/DataInputStream": {
		Parent: "java/io/InputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/io/InputStream;)V"},
			{name: "readBoolean", descriptor: "()Z"},
			{name: "readByte", descriptor: "()B"},
			{name: "readUnsignedByte", descriptor: "()I"},
			{name: "readShort", descriptor: "()S"},
			{name: "readUnsignedShort", descriptor: "()I"},
			{name: "readChar", descriptor: "()C"},
			{name: "readInt", descriptor: "()I"},
			{name: "readLong", descriptor: "()J"},
			{name: "readFully", descriptor: "([B)V"},
			{name: "readFully", descriptor: "([BII)V"},
			{name: "skipBytes", descriptor: "(I)I"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/io/PrintStream": {
		Parent: "java/io/OutputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/io/OutputStream;)V"},
			{name: "print", descriptor: "(Ljava/lang/Object;)V"},
			{name: "print", descriptor: "(Ljava/lang/String;)V"},
			{name: "print", descriptor: "([C)V"},
			{name: "print", descriptor: "(Z)V"},
			{name: "print", descriptor: "(C)V"},
			{name: "print", descriptor: "(I)V"},
			{name: "print", descriptor: "(J)V"},
			{name: "println", descriptor: "()V"},
			{name: "println", descriptor: "(Ljava/lang/Object;)V"},
			{name: "println", descriptor: "(Ljava/lang/String;)V"},
			{name: "println", descriptor: "([C)V"},
			{name: "println", descriptor: "(Z)V"},
			{name: "println", descriptor: "(C)V"},
			{name: "println", descriptor: "(I)V"},
			{name: "println", descriptor: "(J)V"},
			{name: "flush", descriptor: "()V"},
			{name: "close", descriptor: "()V"},
			{name: "checkError", descriptor: "()Z"},
		},
	},
	"java/io/InputStreamReader": {
		Parent:    "java/lang/Object",
		fieldSize: 4,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/io/InputStream;)V"},
			{name: "read", descriptor: "([CII)I"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/io/ByteArrayOutputStream": {
		Parent: "java/io/OutputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "write", descriptor: "(I)V"},
			{name: "write", descriptor: "([B)V"},
			{name: "write", descriptor: "([BII)V"},
			{name: "toByteArray", descriptor: "()[B"},
			{name: "size", descriptor: "()I"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/io/OutputStream": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "write", descriptor: "(I)V"},
			{name: "write", descriptor: "([B)V"},
			{name: "write", descriptor: "([BII)V"},
			{name: "flush", descriptor: "()V"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/io/DataOutputStream": {
		Parent: "java/io/OutputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/io/OutputStream;)V"},
			{name: "write", descriptor: "(I)V"},
			{name: "write", descriptor: "([B)V"},
			{name: "write", descriptor: "([BII)V"},
			{name: "writeBoolean", descriptor: "(Z)V"},
			{name: "writeByte", descriptor: "(I)V"},
			{name: "writeShort", descriptor: "(I)V"},
			{name: "writeChar", descriptor: "(I)V"},
			{name: "writeInt", descriptor: "(I)V"},
			{name: "writeLong", descriptor: "(J)V"},
			{name: "flush", descriptor: "()V"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/lang/Integer": {
		Parent:    "java/lang/Object",
		fieldSize: 4,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(I)V"},
			{name: "byteValue", descriptor: "()B"},
			{name: "shortValue", descriptor: "()S"},
			{name: "intValue", descriptor: "()I"},
			{name: "longValue", descriptor: "()J"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "parseInt", descriptor: "(Ljava/lang/String;)I", access: 0x0008},
			{name: "parseInt", descriptor: "(Ljava/lang/String;I)I", access: 0x0008},
			{name: "toString", descriptor: "(I)Ljava/lang/String;", access: 0x0008},
			{name: "toString", descriptor: "(II)Ljava/lang/String;", access: 0x0008},
			{name: "toHexString", descriptor: "(I)Ljava/lang/String;", access: 0x0008},
			{name: "toOctalString", descriptor: "(I)Ljava/lang/String;", access: 0x0008},
			{name: "toBinaryString", descriptor: "(I)Ljava/lang/String;", access: 0x0008},
		},
	},
	"java/lang/Byte": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "parseByte", descriptor: "(Ljava/lang/String;)B", access: 0x0008},
			{name: "parseByte", descriptor: "(Ljava/lang/String;I)B", access: 0x0008},
		},
	},
	"java/lang/Math": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "abs", descriptor: "(I)I", access: 0x0008},
			{name: "max", descriptor: "(II)I", access: 0x0008},
			{name: "min", descriptor: "(II)I", access: 0x0008},
		},
	},
	"java/util/Random": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(J)V"},
			{name: "setSeed", descriptor: "(J)V"},
			{name: "nextInt", descriptor: "()I"},
			{name: "nextInt", descriptor: "(I)I"},
			{name: "nextBoolean", descriptor: "()Z"},
		},
	},
	"java/util/Date": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(J)V"},
			{name: "getTime", descriptor: "()J"},
			{name: "setTime", descriptor: "(J)V"},
		},
	},
	"java/util/GregorianCalendar": {
		Parent: "java/util/Calendar",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
		},
	},
	"java/util/Vector": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "<init>", descriptor: "(II)V"},
			{name: "addElement", descriptor: "(Ljava/lang/Object;)V"},
			{name: "elementAt", descriptor: "(I)Ljava/lang/Object;"},
			{name: "setElementAt", descriptor: "(Ljava/lang/Object;I)V"},
			{name: "removeElementAt", descriptor: "(I)V"},
			{name: "removeElement", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "removeAllElements", descriptor: "()V"},
			{name: "size", descriptor: "()I"},
			{name: "capacity", descriptor: "()I"},
			{name: "isEmpty", descriptor: "()Z"},
			{name: "contains", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "indexOf", descriptor: "(Ljava/lang/Object;)I"},
			{name: "copyInto", descriptor: "([Ljava/lang/Object;)V"},
			{name: "elements", descriptor: "()Ljava/util/Enumeration;"},
		},
	},
	"java/util/Stack": {
		Parent: "java/util/Vector",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "push", descriptor: "(Ljava/lang/Object;)Ljava/lang/Object;"},
			{name: "pop", descriptor: "()Ljava/lang/Object;"},
			{name: "peek", descriptor: "()Ljava/lang/Object;"},
			{name: "empty", descriptor: "()Z"},
		},
	},
	"java/util/Hashtable": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "put", descriptor: "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"},
			{name: "get", descriptor: "(Ljava/lang/Object;)Ljava/lang/Object;"},
			{name: "remove", descriptor: "(Ljava/lang/Object;)Ljava/lang/Object;"},
			{name: "containsKey", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "contains", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "size", descriptor: "()I"},
			{name: "isEmpty", descriptor: "()Z"},
			{name: "clear", descriptor: "()V"},
			{name: "keys", descriptor: "()Ljava/util/Enumeration;"},
			{name: "elements", descriptor: "()Ljava/util/Enumeration;"},
		},
	},
	"java/util/Enumeration": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "hasMoreElements", descriptor: "()Z"},
			{name: "nextElement", descriptor: "()Ljava/lang/Object;"},
		},
	},
	"java/util/Timer": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "schedule", descriptor: "(Ljava/util/TimerTask;J)V"},
			{name: "schedule", descriptor: "(Ljava/util/TimerTask;JJ)V"},
			{name: "scheduleAtFixedRate", descriptor: "(Ljava/util/TimerTask;JJ)V"},
			{name: "cancel", descriptor: "()V"},
		},
	},
	"java/util/TimerTask": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "run", descriptor: "()V", access: 0x0400},
			{name: "cancel", descriptor: "()Z"},
		},
	},
	"java/util/TimeZone": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "getAvailableIDs", descriptor: "()[Ljava/lang/String;", access: 0x0008},
		},
	},
	"org/kwis/msp/media/Clip": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;I)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Ljava/lang/String;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;[B)V"},
			{name: "setVolume", descriptor: "(I)Z"},
			{name: "getVolume", descriptor: "()I"},
			{name: "setListener", descriptor: "(Lorg/kwis/msp/media/PlayListener;)V"},
		},
	},
	"org/kwis/msp/media/Player": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "play", descriptor: "(Lorg/kwis/msp/media/Clip;Z)Z", access: 0x0008},
			{name: "stop", descriptor: "(Lorg/kwis/msp/media/Clip;)Z", access: 0x0008},
		},
	},
	"org/kwis/msp/lcdui/Jlet": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
		},
	},
	"org/kwis/msp/lwc/Component": {
		Parent: "java/lang/Object",
	},
	"org/kwis/msp/lwc/ContainerComponent": {
		Parent: "org/kwis/msp/lwc/Component",
	},
	"org/kwis/msp/lwc/ShellComponent": {
		Parent: "org/kwis/msp/lwc/ContainerComponent",
	},
	"org/kwis/msp/lwc/FormComponent": {
		Parent: "org/kwis/msp/lwc/ContainerComponent",
	},
	"org/kwis/msp/lwc/TextComponent": {
		Parent: "org/kwis/msp/lwc/Component",
	},
	"org/kwis/msp/lwc/AnnunciatorComponent": {
		Parent: "org/kwis/msp/lwc/ShellComponent",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Z)V"},
			{name: "show", descriptor: "()V"},
			{name: "hide", descriptor: "()V"},
		},
	},
	"org/kwis/msp/handset/BackLight": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "alwaysOn", descriptor: "()V", access: 0x0008},
			{name: "on", descriptor: "()V", access: 0x0008},
			{name: "off", descriptor: "()V", access: 0x0008},
		},
	},
	"org/kwis/msp/handset/LED": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "set", descriptor: "(I)V", access: 0x0008},
		},
	},
	"org/kwis/msp/lwc/TextFieldComponent": {
		Parent: "org/kwis/msp/lwc/TextComponent",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;I)V"},
			{name: "keyNotify", descriptor: "(II)Z"},
		},
	},
	"org/kwis/msp/lwc/LabelComponent": {
		Parent: "org/kwis/msp/lwc/Component",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
		},
	},
	"org/kwis/msp/lwc/ProgressComponent": {
		Parent: "org/kwis/msp/lwc/Component",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(ZI)V"},
			{name: "setStep", descriptor: "(I)V"},
			{name: "getStep", descriptor: "()I"},
			{name: "setMargin", descriptor: "(II)V"},
			{name: "setMaxValue", descriptor: "(I)V"},
			{name: "getMaxValue", descriptor: "()I"},
			{name: "setValue", descriptor: "(I)I"},
			{name: "getValue", descriptor: "()I"},
			{name: "keyNotify", descriptor: "(II)Z"},
		},
	},
	"org/kwis/msp/lwc/DialogComponent": {
		Parent: "org/kwis/msp/lwc/ShellComponent",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(I)V"},
			{
				name: "<init>",
				descriptor: "(Lorg/kwis/msp/lwc/Component;" +
					"Ljava/lang/String;I)V",
			},
			{name: "setButtonString", descriptor: "(ILjava/lang/String;)V"},
			{name: "setType", descriptor: "(I)V"},
			{name: "getType", descriptor: "()I"},
			{name: "setTimeout", descriptor: "(I)V"},
			{name: "getTimeout", descriptor: "()I"},
			{name: "doModal", descriptor: "()I"},
			{name: "getActionState", descriptor: "()I"},
		},
	},
	"com/ktf/kfc/GForm": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(IIII)V"},
		},
	},
	"com/ktf/kfc/GTextField": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{
				name: "<init>",
				descriptor: "(Lcom/ktf/kfc/GMenubarForm;" +
					"Ljava/lang/String;I)V",
			},
			{
				name:       "getGTextListener",
				descriptor: "()Lcom/ktf/kfc/GTextListener;",
			},
		},
	},
	"java/util/Calendar": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "getInstance",
				descriptor: "()Ljava/util/Calendar;",
				access:     0x0008,
			},
			{name: "get", descriptor: "(I)I"},
			{name: "set", descriptor: "(II)V"},
			{name: "setTimeInMillis", descriptor: "(J)V"},
			{name: "getTimeInMillis", descriptor: "()J"},
		},
	},
	"java/lang/Thread": {
		Parent:    "java/lang/Object",
		fieldSize: 16,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Ljava/lang/Runnable;)V"},
			{name: "start", descriptor: "()V"},
			{name: "join", descriptor: "()V"},
			{name: "run", descriptor: "()V"},
			{name: "isAlive", descriptor: "()Z"},
			{name: "sleep", descriptor: "(J)V", access: 0x0108},
			{name: "yield", descriptor: "()V", access: 0x0108},
			{name: "setPriority", descriptor: "(I)V"},
			{
				name:       "currentThread",
				descriptor: "()Ljava/lang/Thread;",
				access:     0x0108,
			},
			{name: "<init>", descriptor: "(Z)V"},
		},
	},
	"java/lang/System": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "arraycopy",
				descriptor: "(Ljava/lang/Object;ILjava/lang/Object;II)V",
				access:     0x0108,
			},
			{
				name:       "currentTimeMillis",
				descriptor: "()J",
				access:     0x0108,
			},
			{name: "gc", descriptor: "()V", access: 0x0008},
			{
				name:       "getProperty",
				descriptor: "(Ljava/lang/String;)Ljava/lang/String;",
				access:     0x0008,
			},
		},
	},
	"java/lang/Runtime": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "getRuntime",
				descriptor: "()Ljava/lang/Runtime;",
				access:     0x0008,
			},
			{name: "freeMemory", descriptor: "()J"},
			{name: "totalMemory", descriptor: "()J"},
			{name: "gc", descriptor: "()V"},
			{name: "exit", descriptor: "(I)V"},
		},
	},
	"org/kwis/msp/lcdui/Card": {
		Parent:    "java/lang/Object",
		fieldSize: 24,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "<init>", descriptor: "(Lorg/kwis/msp/lcdui/Display;)V"},
			{name: "getWidth", descriptor: "()I"},
			{name: "getHeight", descriptor: "()I"},
			{name: "isShown", descriptor: "()Z"},
			{name: "repaint", descriptor: "(IIII)V"},
			{name: "repaint", descriptor: "()V"},
			{name: "serviceRepaints", descriptor: "()V"},
			{name: "showNotify", descriptor: "(Z)V"},
			{name: "keyNotify", descriptor: "(II)Z"},
			{name: "paint", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V", access: 0x0400},
			{name: "setCanvas", descriptor: "(Ljavax/microedition/lcdui/Canvas;)V"},
		},
	},
	"org/kwis/msp/lcdui/Font": {
		Parent:    "java/lang/Object",
		fieldSize: 12,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "getDefaultFont",
				descriptor: "()Lorg/kwis/msp/lcdui/Font;",
				access:     0x0008,
			},
			{
				name:       "getFont",
				descriptor: "(III)Lorg/kwis/msp/lcdui/Font;",
				access:     0x0008,
			},
			{name: "getHeight", descriptor: "()I"},
			{name: "charWidth", descriptor: "(C)I"},
			{name: "stringWidth", descriptor: "(Ljava/lang/String;)I"},
			{
				name:       "substringWidth",
				descriptor: "(Ljava/lang/String;II)I",
			},
			{name: "charsWidth", descriptor: "([CII)I"},
			{name: "getBaselinePosition", descriptor: "()I"},
			{name: "getFace", descriptor: "()I"},
			{name: "getSize", descriptor: "()I"},
			{name: "getStyle", descriptor: "()I"},
			{name: "isBold", descriptor: "()Z"},
			{name: "isItalic", descriptor: "()Z"},
			{name: "isPlain", descriptor: "()Z"},
			{name: "isUnderlined", descriptor: "()Z"},
		},
	},
	"org/kwis/msp/lcdui/Image": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "createImage",
				descriptor: "(II)Lorg/kwis/msp/lcdui/Image;",
				access:     0x0008,
			},
			{
				name: "createImage",
				descriptor: "(Lorg/kwis/msp/lcdui/Image;)" +
					"Lorg/kwis/msp/lcdui/Image;",
				access: 0x0008,
			},
			{
				name:       "createImage",
				descriptor: "(Ljava/lang/String;)Lorg/kwis/msp/lcdui/Image;",
				access:     0x0008,
			},
			{
				name:       "createImage",
				descriptor: "([BII)Lorg/kwis/msp/lcdui/Image;",
				access:     0x0008,
			},
			{name: "getWidth", descriptor: "()I"},
			{name: "getHeight", descriptor: "()I"},
			{
				name:       "getGraphics",
				descriptor: "()Lorg/kwis/msp/lcdui/Graphics;",
			},
		},
	},
	"org/kwis/msp/lcdui/Graphics": {
		Parent:    "java/lang/Object",
		fieldSize: 4,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "<init>",
				descriptor: "(Lorg/kwis/msp/lcdui/Display;)V",
			},
			{
				name:       "<init>",
				descriptor: "(Ljavax/microedition/lcdui/Graphics;)V",
			},
			{
				name:       "getFont",
				descriptor: "()Lorg/kwis/msp/lcdui/Font;",
			},
			{name: "copyArea", descriptor: "(IIIIII)V"},
			{name: "setColor", descriptor: "(I)V"},
			{name: "setColor", descriptor: "(III)V"},
			{
				name:       "setFont",
				descriptor: "(Lorg/kwis/msp/lcdui/Font;)V",
			},
			{name: "setAlpha", descriptor: "(I)V"},
			{name: "fillRect", descriptor: "(IIII)V"},
			{name: "fillRoundRect", descriptor: "(IIIIII)V"},
			{name: "fillArc", descriptor: "(IIIIII)V"},
			{name: "drawLine", descriptor: "(IIII)V"},
			{name: "drawRect", descriptor: "(IIII)V"},
			{name: "drawRoundRect", descriptor: "(IIIIII)V"},
			{name: "drawArc", descriptor: "(IIIIII)V"},
			{name: "drawPolygon", descriptor: "([I[I)V"},
			{name: "drawChar", descriptor: "(CIII)V"},
			{name: "drawChars", descriptor: "([CIIIII)V"},
			{
				name:       "drawString",
				descriptor: "(Ljava/lang/String;III)V",
			},
			{
				name:       "drawSubstring",
				descriptor: "(Ljava/lang/String;IIIII)V",
			},
			{
				name:       "drawImage",
				descriptor: "(Lorg/kwis/msp/lcdui/Image;III)V",
			},
			{name: "setClip", descriptor: "(IIII)V"},
			{name: "clipRect", descriptor: "(IIII)V"},
			{name: "getAlpha", descriptor: "()I"},
			{name: "getBlueComponent", descriptor: "()I"},
			{name: "getColor", descriptor: "()I"},
			{name: "getClipX", descriptor: "()I"},
			{name: "getClipY", descriptor: "()I"},
			{name: "getClipWidth", descriptor: "()I"},
			{name: "getClipHeight", descriptor: "()I"},
			{name: "getGrayScale", descriptor: "()I"},
			{name: "getGreenComponent", descriptor: "()I"},
			{name: "getPixel", descriptor: "(II)I"},
			{name: "getPixels", descriptor: "(IIII[BII)V"},
			{name: "getRedComponent", descriptor: "()I"},
			{name: "getStrokeStyle", descriptor: "()I"},
			{name: "getTranslateX", descriptor: "()I"},
			{name: "getTranslateY", descriptor: "()I"},
			{name: "isXORMode", descriptor: "()Z"},
			{name: "translate", descriptor: "(II)V"},
			{name: "setPixel", descriptor: "(II)V"},
			{name: "setRGBPixels", descriptor: "(IIII[III)V"},
			{name: "setGrayScale", descriptor: "(I)V"},
			{name: "setStrokeStyle", descriptor: "(I)V"},
			{name: "setXORMode", descriptor: "(Z)V"},
			{name: "encodeImage", descriptor: "(IIII)[B"},
			{name: "getRGBPixels", descriptor: "(IIII[III)V"},
		},
	},
	"org/kwis/msp/media/Volume": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "set", descriptor: "(I)V", access: 0x0100},
		},
	},
	"org/kwis/msf/io/Network": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "connect", descriptor: "()I", access: 0x0108},
			{name: "disconnect", descriptor: "()V", access: 0x0108},
		},
	},
	"org/kwis/msp/db/DataBase": {
		Parent:    "java/lang/Object",
		fieldSize: 4,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljavax/microedition/rms/RecordStore;)V"},
			{
				name:       "openDataBase",
				descriptor: "(Ljava/lang/String;IZ)Lorg/kwis/msp/db/DataBase;",
				access:     0x0008,
			},
			{
				name:       "openDataBase",
				descriptor: "(Ljava/lang/String;IZI)Lorg/kwis/msp/db/DataBase;",
				access:     0x0008,
			},
			{name: "getNumberOfRecords", descriptor: "()I"},
			{name: "closeDataBase", descriptor: "()V"},
			{name: "insertRecord", descriptor: "([B)I"},
			{name: "insertRecord", descriptor: "([BII)I"},
			{name: "selectRecord", descriptor: "(I)[B"},
			{name: "updateRecord", descriptor: "(I[B)V"},
			{name: "updateRecord", descriptor: "(I[BII)V"},
			{
				name:       "deleteDataBase",
				descriptor: "(Ljava/lang/String;)V",
				access:     0x0008,
			},
		},
	},
	"org/kwis/msp/lcdui/Display": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "<init>",
				descriptor: "(Lorg/kwis/msp/lcdui/Jlet;Lorg/kwis/msp/lcdui/DisplayProxy;)V",
			},
			{
				name:       "getDisplay",
				descriptor: "(Ljava/lang/String;)Lorg/kwis/msp/lcdui/Display;",
				access:     0x0008,
			},
			{
				name:       "getDefaultDisplay",
				descriptor: "()Lorg/kwis/msp/lcdui/Display;",
				access:     0x0008,
			},
			{name: "isDoubleBuffered", descriptor: "()Z"},
			{
				name:       "getDockedCard",
				descriptor: "()Lorg/kwis/msp/lcdui/Card;",
			},
			{
				name:       "pushCard",
				descriptor: "(Lorg/kwis/msp/lcdui/Card;)V",
			},
			{name: "removeAllCards", descriptor: "()V"},
			{
				name:       "addJletEventListener",
				descriptor: "(Lorg/kwis/msp/lcdui/JletEventListener;)V",
			},
			{name: "getWidth", descriptor: "()I"},
			{name: "getHeight", descriptor: "()I"},
			{
				name:       "callSerially",
				descriptor: "(Ljava/lang/Runnable;)V",
			},
			{
				name:       "getGameAction",
				descriptor: "(I)I",
				access:     0x0108,
			},
			{
				name:       "getKeyCode",
				descriptor: "(I)I",
				access:     0x0108,
			},
			{
				name:       "getKeyName",
				descriptor: "(I)Ljava/lang/String;",
				access:     0x0108,
			},
		},
	},
}
