package ktf

func ktfThrowableSubclassSpec(parent string) ktfHostJavaClassSpec {
	return ktfHostJavaClassSpec{
		Parent: parent,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
		},
	}
}

var HostJavaClassSpecs = map[string]ktfHostJavaClassSpec{
	"java/lang/Object": {
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "getClass", descriptor: "()Ljava/lang/Class;"},
			{name: "hashCode", descriptor: "()I"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "clone", descriptor: "()Ljava/lang/Object;", access: 0x0100},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "notify", descriptor: "()V"},
			{name: "notifyAll", descriptor: "()V"},
			{name: "wait", descriptor: "(J)V"},
			{name: "wait", descriptor: "(JI)V"},
			{name: "wait", descriptor: "()V"},
			{name: "finalize", descriptor: "()V"},
		},
	},
	"java/lang/Class": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "getName", descriptor: "()Ljava/lang/String;"},
			{
				name:       "isAssignableFrom",
				descriptor: "(Ljava/lang/Class;)Z",
			},
			{
				name:       "getResourceAsStream",
				descriptor: "(Ljava/lang/String;)Ljava/io/InputStream;",
			},
			{
				name:       "forName",
				descriptor: "(Ljava/lang/String;)Ljava/lang/Class;",
				access:     0x0108,
			},
			{name: "isArray", descriptor: "()Z"},
			{name: "isInterface", descriptor: "()Z"},
			{
				name:       "isInstance",
				descriptor: "(Ljava/lang/Object;)Z",
			},
			{
				name:       "newInstance",
				descriptor: "()Ljava/lang/Object;",
			},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
		},
	},
	"java/lang/String": {
		Parent:    "java/lang/Object",
		fieldSize: 12,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/StringBuffer;)V"},
			{name: "<init>", descriptor: "([B)V"},
			{name: "<init>", descriptor: "([BII)V"},
			{name: "<init>", descriptor: "([BLjava/lang/String;)V"},
			{name: "<init>", descriptor: "([BIILjava/lang/String;)V"},
			{name: "<init>", descriptor: "([C)V"},
			{name: "<init>", descriptor: "([CII)V"},
			{name: "length", descriptor: "()I"},
			{name: "charAt", descriptor: "(I)C"},
			{name: "compareTo", descriptor: "(Ljava/lang/String;)I"},
			{name: "getChars", descriptor: "(II[CI)V"},
			{name: "hashCode", descriptor: "()I"},
			{name: "substring", descriptor: "(I)Ljava/lang/String;"},
			{name: "substring", descriptor: "(II)Ljava/lang/String;"},
			{name: "trim", descriptor: "()Ljava/lang/String;"},
			{name: "getBytes", descriptor: "()[B"},
			{name: "getBytes", descriptor: "(Ljava/lang/String;)[B"},
			{name: "toCharArray", descriptor: "()[C"},
			{
				name:       "equals",
				descriptor: "(Ljava/lang/Object;)Z",
			},
			{
				name:       "concat",
				descriptor: "(Ljava/lang/String;)Ljava/lang/String;",
			},
			{
				name:       "startsWith",
				descriptor: "(Ljava/lang/String;)Z",
			},
			{
				name:       "startsWith",
				descriptor: "(Ljava/lang/String;I)Z",
			},
			{
				name:       "endsWith",
				descriptor: "(Ljava/lang/String;)Z",
			},
			{name: "indexOf", descriptor: "(I)I"},
			{name: "indexOf", descriptor: "(II)I"},
			{
				name:       "indexOf",
				descriptor: "(Ljava/lang/String;)I",
			},
			{
				name:       "indexOf",
				descriptor: "(Ljava/lang/String;I)I",
			},
			{
				name:       "toLowerCase",
				descriptor: "()Ljava/lang/String;",
			},
			{
				name:       "toUpperCase",
				descriptor: "()Ljava/lang/String;",
			},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{
				name:       "equalsIgnoreCase",
				descriptor: "(Ljava/lang/String;)Z",
			},
			{name: "lastIndexOf", descriptor: "(I)I"},
			{name: "lastIndexOf", descriptor: "(II)I"},
			{
				name:       "regionMatches",
				descriptor: "(ZILjava/lang/String;II)Z",
			},
			{
				name:       "replace",
				descriptor: "(CC)Ljava/lang/String;",
			},
			{name: "intern", descriptor: "()Ljava/lang/String;"},
			{
				name:       "valueOf",
				descriptor: "(I)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(J)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(F)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(D)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(Z)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(C)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "(Ljava/lang/Object;)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "([C)Ljava/lang/String;",
				access:     0x0008,
			},
			{
				name:       "valueOf",
				descriptor: "([CII)Ljava/lang/String;",
				access:     0x0008,
			},
		},
	},
	"java/lang/StringBuffer": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
			{
				name:       "append",
				descriptor: "(Ljava/lang/String;)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(Ljava/lang/Object;)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(Z)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(I)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(J)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(C)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "([C)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "([CII)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(F)Ljava/lang/StringBuffer;",
			},
			{
				name:       "append",
				descriptor: "(D)Ljava/lang/StringBuffer;",
			},
			{
				name:       "delete",
				descriptor: "(II)Ljava/lang/StringBuffer;",
			},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "setLength", descriptor: "(I)V"},
			{name: "length", descriptor: "()I"},
			{name: "capacity", descriptor: "()I"},
			{name: "ensureCapacity", descriptor: "(I)V"},
			{name: "charAt", descriptor: "(I)C"},
			{name: "getChars", descriptor: "(II[CI)V"},
			{name: "setCharAt", descriptor: "(IC)V"},
			{
				name:       "deleteCharAt",
				descriptor: "(I)Ljava/lang/StringBuffer;",
			},
			{
				name:       "reverse",
				descriptor: "()Ljava/lang/StringBuffer;",
			},
			{name: "insert", descriptor: "(IZ)Ljava/lang/StringBuffer;"},
			{name: "insert", descriptor: "(IC)Ljava/lang/StringBuffer;"},
			{
				name:       "insert",
				descriptor: "(I[C)Ljava/lang/StringBuffer;",
			},
			{name: "insert", descriptor: "(II)Ljava/lang/StringBuffer;"},
			{name: "insert", descriptor: "(IJ)Ljava/lang/StringBuffer;"},
			{name: "insert", descriptor: "(IF)Ljava/lang/StringBuffer;"},
			{name: "insert", descriptor: "(ID)Ljava/lang/StringBuffer;"},
			{
				name:       "insert",
				descriptor: "(ILjava/lang/Object;)Ljava/lang/StringBuffer;",
			},
			{
				name:       "insert",
				descriptor: "(ILjava/lang/String;)Ljava/lang/StringBuffer;",
			},
		},
	},
	"java/io/InputStream": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "available", descriptor: "()I"},
			{name: "read", descriptor: "([BII)I"},
			{name: "read", descriptor: "([B)I"},
			{name: "read", descriptor: "()I"},
			{name: "close", descriptor: "()V"},
			{name: "skip", descriptor: "(J)J"},
			{name: "mark", descriptor: "(I)V"},
			{name: "markSupported", descriptor: "()Z"},
			{name: "reset", descriptor: "()V"},
		},
	},
	"java/io/ByteArrayInputStream": {
		Parent: "java/io/InputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "([B)V"},
			{name: "<init>", descriptor: "([BII)V"},
		},
	},
	"java/io/DataInputStream": {
		Parent: "java/io/InputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/io/InputStream;)V"},
			{name: "readBoolean", descriptor: "()Z"},
			{name: "readByte", descriptor: "()B"},
			{name: "readUnsignedByte", descriptor: "()I"},
			{name: "readShort", descriptor: "()S"},
			{name: "readUnsignedShort", descriptor: "()I"},
			{name: "readChar", descriptor: "()C"},
			{name: "readInt", descriptor: "()I"},
			{name: "readLong", descriptor: "()J"},
			{name: "readFloat", descriptor: "()F"},
			{name: "readDouble", descriptor: "()D"},
			{name: "readUTF", descriptor: "()Ljava/lang/String;"},
			{
				name:       "readUTF",
				descriptor: "(Ljava/io/DataInput;)Ljava/lang/String;",
				access:     0x0008,
			},
			{name: "readFully", descriptor: "([B)V"},
			{name: "readFully", descriptor: "([BII)V"},
			{name: "skipBytes", descriptor: "(I)I"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/io/PrintStream": {
		Parent: "java/io/OutputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/io/OutputStream;)V"},
			{name: "print", descriptor: "(Ljava/lang/Object;)V"},
			{name: "print", descriptor: "(Ljava/lang/String;)V"},
			{name: "print", descriptor: "([C)V"},
			{name: "print", descriptor: "(Z)V"},
			{name: "print", descriptor: "(C)V"},
			{name: "print", descriptor: "(I)V"},
			{name: "print", descriptor: "(J)V"},
			{name: "println", descriptor: "()V"},
			{name: "println", descriptor: "(Ljava/lang/Object;)V"},
			{name: "println", descriptor: "(Ljava/lang/String;)V"},
			{name: "println", descriptor: "([C)V"},
			{name: "println", descriptor: "(Z)V"},
			{name: "println", descriptor: "(C)V"},
			{name: "println", descriptor: "(I)V"},
			{name: "println", descriptor: "(J)V"},
			{name: "flush", descriptor: "()V"},
			{name: "close", descriptor: "()V"},
			{name: "checkError", descriptor: "()Z"},
			{name: "setError", descriptor: "()V", access: 0x0004},
			{name: "write", descriptor: "(I)V"},
			{name: "write", descriptor: "([BII)V"},
		},
	},
	"java/io/InputStreamReader": {
		Parent:    "java/io/Reader",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/io/InputStream;)V"},
			{
				name:       "<init>",
				descriptor: "(Ljava/io/InputStream;Ljava/lang/String;)V",
			},
			{name: "read", descriptor: "()I"},
			{name: "read", descriptor: "([C)I"},
			{name: "read", descriptor: "([CII)I"},
			{name: "ready", descriptor: "()Z"},
			{name: "skip", descriptor: "(J)J"},
			{name: "mark", descriptor: "(I)V"},
			{name: "markSupported", descriptor: "()Z"},
			{name: "reset", descriptor: "()V"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/io/ByteArrayOutputStream": {
		Parent: "java/io/OutputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "write", descriptor: "(I)V"},
			{name: "write", descriptor: "([B)V"},
			{name: "write", descriptor: "([BII)V"},
			{name: "toByteArray", descriptor: "()[B"},
			{name: "size", descriptor: "()I"},
			{name: "reset", descriptor: "()V"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/io/OutputStream": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "write", descriptor: "(I)V"},
			{name: "write", descriptor: "([B)V"},
			{name: "write", descriptor: "([BII)V"},
			{name: "flush", descriptor: "()V"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/io/DataOutputStream": {
		Parent: "java/io/OutputStream",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/io/OutputStream;)V"},
			{name: "write", descriptor: "(I)V"},
			{name: "write", descriptor: "([B)V"},
			{name: "write", descriptor: "([BII)V"},
			{name: "writeBoolean", descriptor: "(Z)V"},
			{name: "writeByte", descriptor: "(I)V"},
			{name: "writeShort", descriptor: "(I)V"},
			{name: "writeChar", descriptor: "(I)V"},
			{name: "writeInt", descriptor: "(I)V"},
			{name: "writeLong", descriptor: "(J)V"},
			{name: "writeFloat", descriptor: "(F)V"},
			{name: "writeDouble", descriptor: "(D)V"},
			{name: "writeChars", descriptor: "(Ljava/lang/String;)V"},
			{name: "writeUTF", descriptor: "(Ljava/lang/String;)V"},
			{name: "flush", descriptor: "()V"},
			{name: "close", descriptor: "()V"},
		},
	},
	"java/lang/Integer": {
		Parent:    "java/lang/Object",
		fieldSize: 4,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(I)V"},
			{name: "byteValue", descriptor: "()B"},
			{name: "shortValue", descriptor: "()S"},
			{name: "intValue", descriptor: "()I"},
			{name: "longValue", descriptor: "()J"},
			{name: "floatValue", descriptor: "()F"},
			{name: "doubleValue", descriptor: "()D"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "parseInt", descriptor: "(Ljava/lang/String;)I", access: 0x0008},
			{name: "parseInt", descriptor: "(Ljava/lang/String;I)I", access: 0x0008},
			{name: "toString", descriptor: "(I)Ljava/lang/String;", access: 0x0008},
			{name: "toString", descriptor: "(II)Ljava/lang/String;", access: 0x0008},
			{name: "toHexString", descriptor: "(I)Ljava/lang/String;", access: 0x0008},
			{name: "toOctalString", descriptor: "(I)Ljava/lang/String;", access: 0x0008},
			{name: "toBinaryString", descriptor: "(I)Ljava/lang/String;", access: 0x0008},
			{name: "valueOf", descriptor: "(Ljava/lang/String;)Ljava/lang/Integer;", access: 0x0008},
			{name: "valueOf", descriptor: "(Ljava/lang/String;I)Ljava/lang/Integer;", access: 0x0008},
		},
	},
	"java/lang/Long": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(J)V"},
			{name: "longValue", descriptor: "()J"},
			{name: "floatValue", descriptor: "()F"},
			{name: "doubleValue", descriptor: "()D"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
			{name: "parseLong", descriptor: "(Ljava/lang/String;)J", access: 0x0008},
			{name: "parseLong", descriptor: "(Ljava/lang/String;I)J", access: 0x0008},
			{name: "toString", descriptor: "(J)Ljava/lang/String;", access: 0x0008},
			{name: "toString", descriptor: "(JI)Ljava/lang/String;", access: 0x0008},
		},
	},
	"java/lang/Float": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(F)V"},
			{name: "<init>", descriptor: "(D)V"},
			{name: "byteValue", descriptor: "()B"},
			{name: "shortValue", descriptor: "()S"},
			{name: "intValue", descriptor: "()I"},
			{name: "longValue", descriptor: "()J"},
			{name: "floatValue", descriptor: "()F"},
			{name: "doubleValue", descriptor: "()D"},
			{name: "isNaN", descriptor: "()Z"},
			{name: "isInfinite", descriptor: "()Z"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
			{name: "floatToIntBits", descriptor: "(F)I", access: 0x0008},
			{name: "intBitsToFloat", descriptor: "(I)F", access: 0x0008},
			{name: "isNaN", descriptor: "(F)Z", access: 0x0008},
			{name: "isInfinite", descriptor: "(F)Z", access: 0x0008},
			{name: "parseFloat", descriptor: "(Ljava/lang/String;)F", access: 0x0008},
			{name: "toString", descriptor: "(F)Ljava/lang/String;", access: 0x0008},
			{name: "valueOf", descriptor: "(Ljava/lang/String;)Ljava/lang/Float;", access: 0x0008},
		},
	},
	"java/lang/Double": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(D)V"},
			{name: "byteValue", descriptor: "()B"},
			{name: "shortValue", descriptor: "()S"},
			{name: "intValue", descriptor: "()I"},
			{name: "longValue", descriptor: "()J"},
			{name: "floatValue", descriptor: "()F"},
			{name: "doubleValue", descriptor: "()D"},
			{name: "isNaN", descriptor: "()Z"},
			{name: "isInfinite", descriptor: "()Z"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
			{name: "doubleToLongBits", descriptor: "(D)J", access: 0x0008},
			{name: "longBitsToDouble", descriptor: "(J)D", access: 0x0008},
			{name: "isNaN", descriptor: "(D)Z", access: 0x0008},
			{name: "isInfinite", descriptor: "(D)Z", access: 0x0008},
			{name: "parseDouble", descriptor: "(Ljava/lang/String;)D", access: 0x0008},
			{name: "parseDouble0", descriptor: "(Ljava/lang/String;)D", access: 0x0008},
			{name: "toString", descriptor: "(D)Ljava/lang/String;", access: 0x0008},
			{name: "valueOf", descriptor: "(Ljava/lang/String;)Ljava/lang/Double;", access: 0x0008},
		},
	},
	"java/lang/Byte": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(B)V"},
			{name: "byteValue", descriptor: "()B"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "parseByte", descriptor: "(Ljava/lang/String;)B", access: 0x0008},
			{name: "parseByte", descriptor: "(Ljava/lang/String;I)B", access: 0x0008},
		},
	},
	"java/lang/Math": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "abs", descriptor: "(I)I", access: 0x0008},
			{name: "abs", descriptor: "(J)J", access: 0x0008},
			{name: "abs", descriptor: "(F)F", access: 0x0008},
			{name: "abs", descriptor: "(D)D", access: 0x0008},
			{name: "max", descriptor: "(II)I", access: 0x0008},
			{name: "max", descriptor: "(JJ)J", access: 0x0008},
			{name: "max", descriptor: "(FF)F", access: 0x0008},
			{name: "max", descriptor: "(DD)D", access: 0x0008},
			{name: "min", descriptor: "(II)I", access: 0x0008},
			{name: "min", descriptor: "(JJ)J", access: 0x0008},
			{name: "min", descriptor: "(FF)F", access: 0x0008},
			{name: "min", descriptor: "(DD)D", access: 0x0008},
			{name: "ceil", descriptor: "(D)D", access: 0x0008},
			{name: "floor", descriptor: "(D)D", access: 0x0008},
			{name: "sqrt", descriptor: "(D)D", access: 0x0008},
			{name: "sin", descriptor: "(D)D", access: 0x0008},
			{name: "cos", descriptor: "(D)D", access: 0x0008},
			{name: "tan", descriptor: "(D)D", access: 0x0008},
			{name: "toDegrees", descriptor: "(D)D", access: 0x0008},
			{name: "toRadians", descriptor: "(D)D", access: 0x0008},
		},
	},
	"java/util/Random": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(J)V"},
			{name: "setSeed", descriptor: "(J)V"},
			{name: "next", descriptor: "(I)I", access: 0x0004},
			{name: "nextInt", descriptor: "()I"},
			{name: "nextInt", descriptor: "(I)I"},
			{name: "nextLong", descriptor: "()J"},
			{name: "nextBoolean", descriptor: "()Z"},
		},
	},
	"java/util/Date": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(J)V"},
			{name: "getTime", descriptor: "()J"},
			{name: "setTime", descriptor: "(J)V"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
		},
	},
	"java/util/GregorianCalendar": {
		Parent: "java/util/Calendar",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Ljava/util/TimeZone;)V"},
			{name: "<init>", descriptor: "(III)V"},
			{name: "isLeapYear", descriptor: "(I)Z"},
		},
	},
	"java/util/Vector": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "<init>", descriptor: "(II)V"},
			{name: "addElement", descriptor: "(Ljava/lang/Object;)V"},
			{name: "elementAt", descriptor: "(I)Ljava/lang/Object;"},
			{name: "setElementAt", descriptor: "(Ljava/lang/Object;I)V"},
			{name: "removeElementAt", descriptor: "(I)V"},
			{name: "removeElement", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "removeAllElements", descriptor: "()V"},
			{name: "size", descriptor: "()I"},
			{name: "capacity", descriptor: "()I"},
			{name: "isEmpty", descriptor: "()Z"},
			{name: "contains", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "indexOf", descriptor: "(Ljava/lang/Object;)I"},
			{name: "indexOf", descriptor: "(Ljava/lang/Object;I)I"},
			{name: "lastIndexOf", descriptor: "(Ljava/lang/Object;)I"},
			{name: "lastIndexOf", descriptor: "(Ljava/lang/Object;I)I"},
			{name: "insertElementAt", descriptor: "(Ljava/lang/Object;I)V"},
			{name: "ensureCapacity", descriptor: "(I)V"},
			{name: "firstElement", descriptor: "()Ljava/lang/Object;"},
			{name: "lastElement", descriptor: "()Ljava/lang/Object;"},
			{name: "setSize", descriptor: "(I)V"},
			{name: "trimToSize", descriptor: "()V"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "copyInto", descriptor: "([Ljava/lang/Object;)V"},
			{name: "elements", descriptor: "()Ljava/util/Enumeration;"},
		},
	},
	"java/util/Stack": {
		Parent: "java/util/Vector",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "push", descriptor: "(Ljava/lang/Object;)Ljava/lang/Object;"},
			{name: "pop", descriptor: "()Ljava/lang/Object;"},
			{name: "peek", descriptor: "()Ljava/lang/Object;"},
			{name: "empty", descriptor: "()Z"},
			{name: "search", descriptor: "(Ljava/lang/Object;)I"},
		},
	},
	"java/util/Hashtable": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "put", descriptor: "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"},
			{name: "get", descriptor: "(Ljava/lang/Object;)Ljava/lang/Object;"},
			{name: "remove", descriptor: "(Ljava/lang/Object;)Ljava/lang/Object;"},
			{name: "containsKey", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "contains", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "size", descriptor: "()I"},
			{name: "isEmpty", descriptor: "()Z"},
			{name: "clear", descriptor: "()V"},
			{name: "keys", descriptor: "()Ljava/util/Enumeration;"},
			{name: "elements", descriptor: "()Ljava/util/Enumeration;"},
			{name: "rehash", descriptor: "()V", access: 0x0004},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
		},
	},
	"java/util/Enumeration": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "hasMoreElements", descriptor: "()Z"},
			{name: "nextElement", descriptor: "()Ljava/lang/Object;"},
		},
	},
	"java/util/Timer": {
		Parent:    "java/lang/Object",
		fieldSize: 4,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "schedule", descriptor: "(Ljava/util/TimerTask;J)V"},
			{name: "schedule", descriptor: "(Ljava/util/TimerTask;JJ)V"},
			{name: "schedule", descriptor: "(Ljava/util/TimerTask;Ljava/util/Date;)V"},
			{name: "schedule", descriptor: "(Ljava/util/TimerTask;Ljava/util/Date;J)V"},
			{name: "scheduleAtFixedRate", descriptor: "(Ljava/util/TimerTask;JJ)V"},
			{name: "scheduleAtFixedRate", descriptor: "(Ljava/util/TimerTask;Ljava/util/Date;J)V"},
			{name: "cancel", descriptor: "()V"},
		},
	},
	"java/util/TimerTask": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "run", descriptor: "()V", access: 0x0400},
			{name: "cancel", descriptor: "()Z"},
			{name: "scheduledExecutionTime", descriptor: "()J"},
		},
	},
	"java/util/TimeZone": {
		Parent: "java/lang/Object",
		access: 0x0401,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "getAvailableIDs", descriptor: "()[Ljava/lang/String;", access: 0x0008},
			{name: "getAvailableIDs", descriptor: "(I)[Ljava/lang/String;", access: 0x0008},
			{name: "getDefault", descriptor: "()Ljava/util/TimeZone;", access: 0x0008},
			{name: "getTimeZone", descriptor: "(Ljava/lang/String;)Ljava/util/TimeZone;", access: 0x0008},
			{name: "initialize", descriptor: "()V", access: 0x0008},
			{name: "getID", descriptor: "()Ljava/lang/String;"},
			{name: "setID", descriptor: "(Ljava/lang/String;)V"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "getOffset", descriptor: "(IIIIII)I", access: 0x0401},
			{name: "getRawOffset", descriptor: "()I", access: 0x0401},
			{name: "useDaylightTime", descriptor: "()Z", access: 0x0401},
		},
	},
	"org/kwis/msp/media/Clip": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;I)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Ljava/lang/String;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;[B)V"},
			{name: "setVolume", descriptor: "(I)Z"},
			{name: "getVolume", descriptor: "()I"},
			{name: "setListener", descriptor: "(Lorg/kwis/msp/media/PlayListener;)V"},
			{name: "availableDataSize", descriptor: "()I"},
			{name: "clearData", descriptor: "()V"},
			{name: "putData", descriptor: "([BII)I"},
			{name: "getData", descriptor: "([BII)I"},
			{name: "setBuffer", descriptor: "([BI)Z"},
			{name: "getType", descriptor: "()Ljava/lang/String;"},
			{name: "setPosition", descriptor: "(I)Z"},
			{name: "playStart", descriptor: "(Z)Z"},
			{name: "recordStart", descriptor: "()Z"},
			{name: "playUpdate", descriptor: "(II)Z"},
			{name: "getPlayerID", descriptor: "(Ljava/lang/String;)I"},
			{name: "atomicPutUpdate", descriptor: "(I)V"},
			{name: "mediaWriteData", descriptor: "()I"},
			{name: "atomicGetUpdate", descriptor: "(I)V"},
			{name: "mediaReadData", descriptor: "()I"},
			{name: "mediaFreeze", descriptor: "()I"},
			{
				name:       "control",
				descriptor: "(IILjava/lang/Object;Ljava/lang/Object;)I",
				access:     0x0008,
			},
		},
	},
	"org/kwis/msp/media/Player": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "play", descriptor: "(Lorg/kwis/msp/media/Clip;Z)Z", access: 0x0008},
			{name: "stop", descriptor: "(Lorg/kwis/msp/media/Clip;)Z", access: 0x0008},
			{name: "pause", descriptor: "(Lorg/kwis/msp/media/Clip;)Z", access: 0x0008},
			{name: "resume", descriptor: "(Lorg/kwis/msp/media/Clip;)Z", access: 0x0008},
		},
	},
	"org/kwis/msp/lcdui/Jlet": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
		},
	},
	"org/kwis/msp/lwc/Component": {
		Parent:              "java/lang/Object",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V", access: 0x0004},
			{name: "calcPreferredSize", descriptor: "(I)V", access: 0x0004},
			{name: "canHandleInput", descriptor: "()Z"},
			{name: "configure", descriptor: "(IIIII)V"},
			{name: "focusNotify", descriptor: "(Z)V"},
			{name: "getBackground", descriptor: "()I"},
			{name: "getCard", descriptor: "()Lorg/kwis/msp/lcdui/Card;"},
			{name: "getForeground", descriptor: "()I"},
			{name: "getHeight", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "(I)I"},
			{name: "getPreferredWidth", descriptor: "()I"},
			{name: "getWidth", descriptor: "()I"},
			{name: "getX", descriptor: "()I"},
			{name: "getXOnScreen", descriptor: "()I"},
			{name: "getY", descriptor: "()I"},
			{name: "getYOnScreen", descriptor: "()I"},
			{name: "hasFocus", descriptor: "()Z"},
			{name: "invalidate", descriptor: "()V"},
			{name: "isShown", descriptor: "()Z"},
			{name: "isValid", descriptor: "()Z", access: 0x0004},
		},
	},
	"org/kwis/msp/lwc/ContainerComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V", access: 0x0004},
			{name: "addComponent", descriptor: "(Lorg/kwis/msp/lwc/Component;)I"},
			{name: "addComponent", descriptor: "(ILorg/kwis/msp/lwc/Component;)V"},
			{name: "controlInset", descriptor: "(Z)V", access: 0x0004},
			{name: "getComponent", descriptor: "(I)Lorg/kwis/msp/lwc/Component;"},
			{name: "getIndexOf", descriptor: "(Lorg/kwis/msp/lwc/Component;)I"},
			{name: "getNextTraversalComponent", descriptor: "()Lorg/kwis/msp/lwc/Component;", access: 0x0004},
			{name: "getNumberOfComponent", descriptor: "()I"},
			{name: "getPrevTraversalComponent", descriptor: "()Lorg/kwis/msp/lwc/Component;", access: 0x0004},
			{name: "keyNotify", descriptor: "(II)Z", access: 0x0004},
			{name: "paint", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V", access: 0x0004},
			{name: "paintFrame", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V", access: 0x0004},
			{name: "processEvent", descriptor: "(IIII)Z", access: 0x0004},
			{name: "removeAllComponents", descriptor: "()V"},
			{name: "removeComponent", descriptor: "(Lorg/kwis/msp/lwc/Component;)V"},
			{name: "removeComponent", descriptor: "(I)V"},
			{name: "repaint", descriptor: "()V"},
			{name: "repaint", descriptor: "(IIII)V"},
			{name: "scrollTo", descriptor: "(II)Z", access: 0x0004},
			{name: "setComponent", descriptor: "(ILorg/kwis/msp/lwc/Component;)V"},
			{name: "useFrame", descriptor: "(Z)V"},
			{name: "validate", descriptor: "()V"},
		},
	},
	"org/kwis/msp/lwc/ShellComponent": {
		Parent:              "org/kwis/msp/lwc/ContainerComponent",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Z)V"},
			{name: "<init>", descriptor: "(ZZ)V"},
			{name: "<init>", descriptor: "(IIII)V"},
			{name: "<init>", descriptor: "(IIIIZ)V"},
			{name: "addComponent", descriptor: "(Lorg/kwis/msp/lwc/Component;)I"},
			{name: "addComponent", descriptor: "(ILorg/kwis/msp/lwc/Component;)V"},
			{name: "configure", descriptor: "(IIIII)V"},
			{name: "controlInset", descriptor: "(Z)V", access: 0x0004},
			{name: "getCard", descriptor: "()Lorg/kwis/msp/lcdui/Card;"},
			{name: "getCommand", descriptor: "()Lorg/kwis/msp/lwc/Component;"},
			{name: "getNextTraversalComponent", descriptor: "()Lorg/kwis/msp/lwc/Component;", access: 0x0004},
			{name: "getPrevTraversalComponent", descriptor: "()Lorg/kwis/msp/lwc/Component;", access: 0x0004},
			{name: "getTitle", descriptor: "()Lorg/kwis/msp/lwc/Component;"},
			{name: "getWorkComponent", descriptor: "()Lorg/kwis/msp/lwc/Component;"},
			{name: "getX", descriptor: "()I"},
			{name: "getY", descriptor: "()I"},
			{name: "grabKey", descriptor: "(I)V"},
			{name: "hide", descriptor: "()V"},
			{name: "isShown", descriptor: "()Z"},
			{name: "keyNotify", descriptor: "(II)Z", access: 0x0004},
			{name: "layout", descriptor: "()V"},
			{name: "processEvent", descriptor: "(IIII)Z", access: 0x0004},
			{name: "removeAllComponents", descriptor: "()V"},
			{name: "removeComponent", descriptor: "(Lorg/kwis/msp/lwc/Component;)V"},
			{name: "repaint", descriptor: "(IIII)V"},
			{name: "serviceRepaints", descriptor: "()V"},
			{name: "setCommand", descriptor: "(Lorg/kwis/msp/lwc/Component;Z)V"},
			{name: "setGrabKeyListener", descriptor: "(Lorg/kwis/msp/lwc/GrabKeyListener;Ljava/lang/Object;)V"},
			{name: "setTitle", descriptor: "(Lorg/kwis/msp/lwc/Component;)V"},
			{name: "setTitle", descriptor: "(Ljava/lang/String;)V"},
			{name: "setWorkComponent", descriptor: "(Lorg/kwis/msp/lwc/Component;)V"},
			{name: "show", descriptor: "()V"},
			{name: "showNotify", descriptor: "(Z)V"},
			{name: "ungrabKey", descriptor: "(I)V"},
		},
	},
	"org/kwis/msp/lwc/FormComponent": {
		Parent:              "org/kwis/msp/lwc/ContainerComponent",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Z)V"},
			{name: "calcPreferredSize", descriptor: "(I)V", access: 0x0004},
			{name: "focusNotify", descriptor: "(Z)V"},
			{name: "getGab", descriptor: "()I"},
			{name: "getNextTraversalComponent", descriptor: "()Lorg/kwis/msp/lwc/Component;", access: 0x0004},
			{name: "getPacked", descriptor: "()Z"},
			{name: "getPrevTraversalComponent", descriptor: "()Lorg/kwis/msp/lwc/Component;", access: 0x0004},
			{name: "keyNotify", descriptor: "(II)Z", access: 0x0004},
			{name: "layout", descriptor: "()V"},
			{name: "layoutChildHorizontal", descriptor: "()V", access: 0x0004},
			{name: "layoutChildVertical", descriptor: "()V", access: 0x0004},
			{name: "paint", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "removeAllComponents", descriptor: "()V"},
			{name: "scrollTo", descriptor: "(II)Z", access: 0x0004},
			{name: "setFocus", descriptor: "(Lorg/kwis/msp/lwc/Component;)V"},
			{name: "setGab", descriptor: "(I)V"},
			{name: "setPacked", descriptor: "(Z)V"},
		},
	},
	"org/kwis/msp/lwc/TextComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		// Both are per-component handset state, and both have been observed
		// being read through a receiver by the guest's own getfield helper:
		// the helper loads the record's offset word and indexes the
		// receiver's field block with it (issues #156 and #168).
		fields: []ktfHostJavaFieldSpec{
			{
				name:       "imHandler",
				descriptor: "Lorg/kwis/msp/lcdui/InputMethodHandler;",
			},
			{name: "m_td", descriptor: "[C"},
		},
		methods: []ktfHostJavaMethodSpec{
			{name: "delete", descriptor: "(II)V"},
			{name: "focusNotify", descriptor: "(Z)V"},
			{name: "getConstraint", descriptor: "()I"},
			{name: "getFont", descriptor: "()Lorg/kwis/msp/lcdui/Font;"},
			{name: "getMaxLength", descriptor: "()I"},
			{name: "getString", descriptor: "()Ljava/lang/String;"},
			{name: "insert", descriptor: "([CIII)V"},
			{name: "keyNotify", descriptor: "(II)Z"},
			{name: "setFont", descriptor: "(Lorg/kwis/msp/lcdui/Font;)V"},
			{name: "setMaxLength", descriptor: "(I)V"},
			{name: "setString", descriptor: "(Ljava/lang/String;)V"},
			{name: "showNotify", descriptor: "(Z)V", access: 0x0004},
		},
	},
	"org/kwis/msp/lwc/AnnunciatorComponent": {
		Parent: "org/kwis/msp/lwc/ShellComponent",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Z)V"},
			{name: "show", descriptor: "()V"},
			{name: "hide", descriptor: "()V"},
		},
	},
	"org/kwis/msp/handset/BackLight": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "alwaysOn", descriptor: "()V", access: 0x0008},
			{name: "on", descriptor: "()V", access: 0x0008},
			{name: "off", descriptor: "()V", access: 0x0008},
		},
	},
	"org/kwis/msp/handset/LED": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "set", descriptor: "(I)V", access: 0x0008},
			{name: "get", descriptor: "()I", access: 0x0008},
			{name: "getCount", descriptor: "()I", access: 0x0008},
		},
	},
	"org/kwis/msp/lwc/TextFieldComponent": {
		Parent: "org/kwis/msp/lwc/TextComponent",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;I)V"},
			{name: "keyNotify", descriptor: "(II)Z"},
		},
	},
	"org/kwis/msp/lwc/LabelComponent": {
		Parent: "org/kwis/msp/lwc/Component",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
		},
	},
	"org/kwis/msp/lwc/ProgressComponent": {
		Parent: "org/kwis/msp/lwc/Component",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(ZI)V"},
			{name: "setStep", descriptor: "(I)V"},
			{name: "getStep", descriptor: "()I"},
			{name: "setMargin", descriptor: "(II)V"},
			{name: "setMaxValue", descriptor: "(I)V"},
			{name: "getMaxValue", descriptor: "()I"},
			{name: "setValue", descriptor: "(I)I"},
			{name: "getValue", descriptor: "()I"},
			{name: "keyNotify", descriptor: "(II)Z"},
		},
	},
	"org/kwis/msp/lwc/DialogComponent": {
		Parent: "org/kwis/msp/lwc/ShellComponent",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(I)V"},
			{
				name: "<init>",
				descriptor: "(Lorg/kwis/msp/lwc/Component;" +
					"Ljava/lang/String;I)V",
			},
			{name: "setButtonString", descriptor: "(ILjava/lang/String;)V"},
			{name: "setType", descriptor: "(I)V"},
			{name: "getType", descriptor: "()I"},
			{name: "setTimeout", descriptor: "(I)V"},
			{name: "getTimeout", descriptor: "()I"},
			{name: "doModal", descriptor: "()I"},
			{name: "getActionState", descriptor: "()I"},
		},
	},
	"com/ktf/kfc/GForm": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(IIII)V"},
		},
	},
	"com/ktf/kfc/GTextField": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{
				name: "<init>",
				descriptor: "(Lcom/ktf/kfc/GMenubarForm;" +
					"Ljava/lang/String;I)V",
			},
			{
				name:       "getGTextListener",
				descriptor: "()Lcom/ktf/kfc/GTextListener;",
			},
		},
	},
	"java/util/Calendar": {
		Parent: "java/lang/Object",
		access: 0x0401,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V", access: 0x0004},
			{name: "<init>", descriptor: "(Ljava/util/TimeZone;)V", access: 0x0004},
			{
				name:       "getInstance",
				descriptor: "()Ljava/util/Calendar;",
				access:     0x0008,
			},
			{name: "getInstance", descriptor: "(Ljava/util/TimeZone;)Ljava/util/Calendar;", access: 0x0008},
			{name: "initialize", descriptor: "()V", access: 0x0008},
			{name: "after", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "before", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
			{name: "get", descriptor: "(I)I"},
			{name: "internalGet", descriptor: "(I)I", access: 0x0004},
			{name: "set", descriptor: "(II)V"},
			{name: "set", descriptor: "(III)V", access: 0x0004},
			{name: "getTime", descriptor: "()Ljava/util/Date;"},
			{name: "setTime", descriptor: "(Ljava/util/Date;)V"},
			{name: "setTimeInMillis", descriptor: "(J)V"},
			{name: "getTimeInMillis", descriptor: "()J"},
			{name: "getTimeZone", descriptor: "()Ljava/util/TimeZone;"},
			{name: "setTimeZone", descriptor: "(Ljava/util/TimeZone;)V"},
			{name: "getFirstDayOfWeek", descriptor: "()I", access: 0x0004},
			{name: "getMinimalDaysInFirstWeek", descriptor: "()I", access: 0x0004},
			{name: "isLenient", descriptor: "()Z", access: 0x0004},
			{name: "isSet", descriptor: "(I)Z", access: 0x0004},
			{name: "complete", descriptor: "()V", access: 0x0004},
			{name: "computeFields", descriptor: "()V", access: 0x0404},
			{name: "computeTime", descriptor: "()V", access: 0x0404},
			{name: "getGreatestMinimum", descriptor: "(I)I", access: 0x0404},
			{name: "getLeastMaximum", descriptor: "(I)I", access: 0x0404},
			{name: "getMaximum", descriptor: "(I)I", access: 0x0404},
			{name: "getMinimum", descriptor: "(I)I", access: 0x0404},
		},
	},
	"java/lang/Thread": {
		Parent:    "java/lang/Object",
		fieldSize: 16,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Ljava/lang/Runnable;)V"},
			{name: "start", descriptor: "()V"},
			{name: "join", descriptor: "()V"},
			{name: "run", descriptor: "()V"},
			{name: "isAlive", descriptor: "()Z"},
			{name: "activeCount", descriptor: "()I", access: 0x0108},
			{name: "getPriority", descriptor: "()I"},
			{name: "sleep", descriptor: "(J)V", access: 0x0108},
			{name: "yield", descriptor: "()V", access: 0x0108},
			{name: "setPriority", descriptor: "(I)V"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{
				name:       "currentThread",
				descriptor: "()Ljava/lang/Thread;",
				access:     0x0108,
			},
			{name: "<init>", descriptor: "(Z)V"},
		},
	},
	"java/lang/System": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "arraycopy",
				descriptor: "(Ljava/lang/Object;ILjava/lang/Object;II)V",
				access:     0x0108,
			},
			{
				name:       "currentTimeMillis",
				descriptor: "()J",
				access:     0x0108,
			},
			{name: "gc", descriptor: "()V", access: 0x0008},
			{
				name:       "getProperty",
				descriptor: "(Ljava/lang/String;)Ljava/lang/String;",
				access:     0x0008,
			},
			{name: "exit", descriptor: "(I)V", access: 0x0008},
			{
				name:       "identityHashCode",
				descriptor: "(Ljava/lang/Object;)I",
				access:     0x0008,
			},
		},
	},
	"java/lang/Runtime": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "getRuntime",
				descriptor: "()Ljava/lang/Runtime;",
				access:     0x0008,
			},
			{name: "freeMemory", descriptor: "()J"},
			{name: "totalMemory", descriptor: "()J"},
			{name: "gc", descriptor: "()V"},
			{name: "exit", descriptor: "(I)V"},
		},
	},
	"org/kwis/msp/lcdui/Card": {
		Parent:    "java/lang/Object",
		fieldSize: 24,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "<init>", descriptor: "(Lorg/kwis/msp/lcdui/Display;)V"},
			{name: "getWidth", descriptor: "()I"},
			{name: "getHeight", descriptor: "()I"},
			{name: "isShown", descriptor: "()Z"},
			{name: "repaint", descriptor: "(IIII)V"},
			{name: "repaint", descriptor: "()V"},
			{name: "serviceRepaints", descriptor: "()V"},
			{name: "showNotify", descriptor: "(Z)V"},
			{name: "keyNotify", descriptor: "(II)Z"},
			{name: "paint", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V", access: 0x0400},
			{name: "setCanvas", descriptor: "(Ljavax/microedition/lcdui/Canvas;)V"},
		},
	},
	"org/kwis/msp/lcdui/Font": {
		Parent:    "java/lang/Object",
		fieldSize: 12,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "getDefaultFont",
				descriptor: "()Lorg/kwis/msp/lcdui/Font;",
				access:     0x0008,
			},
			{
				name:       "getFont",
				descriptor: "(III)Lorg/kwis/msp/lcdui/Font;",
				access:     0x0008,
			},
			{name: "getHeight", descriptor: "()I"},
			{name: "charWidth", descriptor: "(C)I"},
			{name: "stringWidth", descriptor: "(Ljava/lang/String;)I"},
			{
				name:       "substringWidth",
				descriptor: "(Ljava/lang/String;II)I",
			},
			{name: "charsWidth", descriptor: "([CII)I"},
			{name: "getBaselinePosition", descriptor: "()I"},
			{name: "getFace", descriptor: "()I"},
			{name: "getSize", descriptor: "()I"},
			{name: "getStyle", descriptor: "()I"},
			{name: "isBold", descriptor: "()Z"},
			{name: "isItalic", descriptor: "()Z"},
			{name: "isPlain", descriptor: "()Z"},
			{name: "isUnderlined", descriptor: "()Z"},
		},
	},
	"org/kwis/msp/lcdui/Image": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "createImage",
				descriptor: "(II)Lorg/kwis/msp/lcdui/Image;",
				access:     0x0008,
			},
			{
				name: "createImage",
				descriptor: "(Lorg/kwis/msp/lcdui/Image;)" +
					"Lorg/kwis/msp/lcdui/Image;",
				access: 0x0008,
			},
			{
				name:       "createImage",
				descriptor: "(Ljava/lang/String;)Lorg/kwis/msp/lcdui/Image;",
				access:     0x0008,
			},
			{
				name:       "createImage",
				descriptor: "([BII)Lorg/kwis/msp/lcdui/Image;",
				access:     0x0008,
			},
			{name: "getWidth", descriptor: "()I"},
			{name: "getHeight", descriptor: "()I"},
			{
				name:       "getGraphics",
				descriptor: "()Lorg/kwis/msp/lcdui/Graphics;",
			},
		},
	},
	"org/kwis/msp/lcdui/Graphics": {
		Parent:    "java/lang/Object",
		fieldSize: 4,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "<init>",
				descriptor: "(Lorg/kwis/msp/lcdui/Display;)V",
			},
			{
				name:       "<init>",
				descriptor: "(Ljavax/microedition/lcdui/Graphics;)V",
			},
			{
				name:       "getFont",
				descriptor: "()Lorg/kwis/msp/lcdui/Font;",
			},
			{name: "copyArea", descriptor: "(IIIIII)V"},
			{name: "setColor", descriptor: "(I)V"},
			{name: "setColor", descriptor: "(III)V"},
			{
				name:       "setFont",
				descriptor: "(Lorg/kwis/msp/lcdui/Font;)V",
			},
			{name: "setAlpha", descriptor: "(I)V"},
			{name: "fillRect", descriptor: "(IIII)V"},
			{name: "fillRoundRect", descriptor: "(IIIIII)V"},
			{name: "fillArc", descriptor: "(IIIIII)V"},
			{name: "drawLine", descriptor: "(IIII)V"},
			{name: "drawRect", descriptor: "(IIII)V"},
			{name: "drawRoundRect", descriptor: "(IIIIII)V"},
			{name: "drawArc", descriptor: "(IIIIII)V"},
			{name: "drawPolygon", descriptor: "([I[I)V"},
			{name: "drawChar", descriptor: "(CIII)V"},
			{name: "drawChars", descriptor: "([CIIIII)V"},
			{
				name:       "drawString",
				descriptor: "(Ljava/lang/String;III)V",
			},
			{
				name:       "drawSubstring",
				descriptor: "(Ljava/lang/String;IIIII)V",
			},
			{
				name:       "drawImage",
				descriptor: "(Lorg/kwis/msp/lcdui/Image;III)V",
			},
			{name: "setClip", descriptor: "(IIII)V"},
			{name: "clipRect", descriptor: "(IIII)V"},
			{name: "getAlpha", descriptor: "()I"},
			{name: "getBlueComponent", descriptor: "()I"},
			{name: "getColor", descriptor: "()I"},
			{name: "getClipX", descriptor: "()I"},
			{name: "getClipY", descriptor: "()I"},
			{name: "getClipWidth", descriptor: "()I"},
			{name: "getClipHeight", descriptor: "()I"},
			{name: "getGrayScale", descriptor: "()I"},
			{name: "getGreenComponent", descriptor: "()I"},
			{name: "getPixel", descriptor: "(II)I"},
			{name: "getPixels", descriptor: "(IIII[BII)V"},
			{name: "getRedComponent", descriptor: "()I"},
			{name: "getStrokeStyle", descriptor: "()I"},
			{name: "getTranslateX", descriptor: "()I"},
			{name: "getTranslateY", descriptor: "()I"},
			{name: "isXORMode", descriptor: "()Z"},
			{name: "translate", descriptor: "(II)V"},
			{name: "setPixel", descriptor: "(II)V"},
			{name: "setRGBPixels", descriptor: "(IIII[III)V"},
			{name: "setGrayScale", descriptor: "(I)V"},
			{name: "setStrokeStyle", descriptor: "(I)V"},
			{name: "setXORMode", descriptor: "(Z)V"},
			{name: "encodeImage", descriptor: "(IIII)[B"},
			{name: "getRGBPixels", descriptor: "(IIII[III)V"},
		},
	},
	"org/kwis/msp/media/Volume": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "set", descriptor: "(I)V", access: 0x0100},
		},
	},
	"org/kwis/msf/io/Network": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "connect", descriptor: "()I", access: 0x0108},
			{name: "disconnect", descriptor: "()V", access: 0x0108},
		},
	},
	"org/kwis/msp/db/DataBase": {
		Parent:    "java/lang/Object",
		fieldSize: 4,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljavax/microedition/rms/RecordStore;)V"},
			{
				name:       "openDataBase",
				descriptor: "(Ljava/lang/String;IZ)Lorg/kwis/msp/db/DataBase;",
				access:     0x0008,
			},
			{
				name:       "openDataBase",
				descriptor: "(Ljava/lang/String;IZI)Lorg/kwis/msp/db/DataBase;",
				access:     0x0008,
			},
			{name: "getNumberOfRecords", descriptor: "()I"},
			{name: "closeDataBase", descriptor: "()V"},
			{name: "insertRecord", descriptor: "([B)I"},
			{name: "insertRecord", descriptor: "([BII)I"},
			{name: "selectRecord", descriptor: "(I)[B"},
			{name: "updateRecord", descriptor: "(I[B)V"},
			{name: "updateRecord", descriptor: "(I[BII)V"},
			{
				name:       "deleteDataBase",
				descriptor: "(Ljava/lang/String;)V",
				access:     0x0008,
			},
		},
	},
	"org/kwis/msp/lcdui/Display": {
		Parent:    "java/lang/Object",
		fieldSize: 8,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "<init>",
				descriptor: "(Lorg/kwis/msp/lcdui/Jlet;Lorg/kwis/msp/lcdui/DisplayProxy;)V",
			},
			{
				name:       "getDisplay",
				descriptor: "(Ljava/lang/String;)Lorg/kwis/msp/lcdui/Display;",
				access:     0x0008,
			},
			{
				name:       "getDefaultDisplay",
				descriptor: "()Lorg/kwis/msp/lcdui/Display;",
				access:     0x0008,
			},
			{name: "isDoubleBuffered", descriptor: "()Z"},
			{
				name:       "getDockedCard",
				descriptor: "()Lorg/kwis/msp/lcdui/Card;",
			},
			{
				name:       "pushCard",
				descriptor: "(Lorg/kwis/msp/lcdui/Card;)V",
			},
			{name: "removeAllCards", descriptor: "()V"},
			{
				name:       "addJletEventListener",
				descriptor: "(Lorg/kwis/msp/lcdui/JletEventListener;)V",
			},
			{name: "getWidth", descriptor: "()I"},
			{name: "getHeight", descriptor: "()I"},
			{
				name:       "callSerially",
				descriptor: "(Ljava/lang/Runnable;)V",
			},
			{
				name:       "getGameAction",
				descriptor: "(I)I",
				access:     0x0108,
			},
			{
				name:       "getKeyCode",
				descriptor: "(I)I",
				access:     0x0108,
			},
			{
				name:       "getKeyName",
				descriptor: "(I)Ljava/lang/String;",
				access:     0x0108,
			},
		},
	},

	// Parent-only declarations. Method bodies resolve lazily through the
	// native dispatcher; what matters here is the hierarchy so that guest
	// checkcast, catch clauses, and receiver-compatibility checks walk the
	// same tree the reference platform ships.
	"java/lang/Boolean": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Z)V"},
			{name: "booleanValue", descriptor: "()Z"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
		},
	},
	"java/lang/Character": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(C)V"},
			{name: "charValue", descriptor: "()C"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "digit", descriptor: "(CI)I", access: 0x0008},
			{name: "isDigit", descriptor: "(C)Z", access: 0x0008},
			{name: "isLowerCase", descriptor: "(C)Z", access: 0x0008},
			{name: "isUpperCase", descriptor: "(C)Z", access: 0x0008},
			{name: "toLowerCase", descriptor: "(C)C", access: 0x0008},
			{name: "toUpperCase", descriptor: "(C)C", access: 0x0008},
		},
	},
	"java/lang/Short": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(S)V"},
			{name: "shortValue", descriptor: "()S"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "hashCode", descriptor: "()I"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
			{name: "parseShort", descriptor: "(Ljava/lang/String;)S", access: 0x0008},
			{name: "parseShort", descriptor: "(Ljava/lang/String;I)S", access: 0x0008},
		},
	},
	"java/lang/Runnable": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "run", descriptor: "()V", access: 0x0401},
		},
	},

	"java/lang/Throwable": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
			{name: "getMessage", descriptor: "()Ljava/lang/String;"},
			{name: "printStackTrace", descriptor: "()V"},
			{name: "toString", descriptor: "()Ljava/lang/String;"},
		},
	},
	"java/lang/Exception": ktfThrowableSubclassSpec("java/lang/Throwable"),
	"java/lang/Error":     ktfThrowableSubclassSpec("java/lang/Throwable"),
	"java/lang/RuntimeException": ktfThrowableSubclassSpec(
		"java/lang/Exception",
	),
	"java/lang/ArithmeticException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/ArrayStoreException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/ClassCastException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/ClassNotFoundException": ktfThrowableSubclassSpec(
		"java/lang/Exception",
	),
	"java/lang/IllegalAccessException": ktfThrowableSubclassSpec(
		"java/lang/Exception",
	),
	"java/lang/IllegalArgumentException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/IllegalMonitorStateException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/IllegalStateException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/IllegalThreadStateException": ktfThrowableSubclassSpec(
		"java/lang/IllegalArgumentException",
	),
	"java/lang/IndexOutOfBoundsException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/ArrayIndexOutOfBoundsException": ktfThrowableSubclassSpec(
		"java/lang/IndexOutOfBoundsException",
	),
	"java/lang/StringIndexOutOfBoundsException": ktfThrowableSubclassSpec(
		"java/lang/IndexOutOfBoundsException",
	),
	"java/lang/InstantiationException": ktfThrowableSubclassSpec(
		"java/lang/Exception",
	),
	"java/lang/InterruptedException": ktfThrowableSubclassSpec(
		"java/lang/Exception",
	),
	"java/lang/NegativeArraySizeException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/NullPointerException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/NumberFormatException": ktfThrowableSubclassSpec(
		"java/lang/IllegalArgumentException",
	),
	"java/lang/SecurityException": ktfThrowableSubclassSpec(
		"java/lang/RuntimeException",
	),
	"java/lang/VirtualMachineError": ktfThrowableSubclassSpec("java/lang/Error"),
	"java/lang/OutOfMemoryError": ktfThrowableSubclassSpec(
		"java/lang/VirtualMachineError",
	),

	"java/io/IOException":  ktfThrowableSubclassSpec("java/lang/Exception"),
	"java/io/EOFException": ktfThrowableSubclassSpec("java/io/IOException"),
	"java/io/InterruptedIOException": ktfThrowableSubclassSpec(
		"java/io/IOException",
	),
	"java/io/UTFDataFormatException": ktfThrowableSubclassSpec(
		"java/io/IOException",
	),
	"java/io/UnavailableException": ktfThrowableSubclassSpec(
		"java/io/IOException",
	),
	"java/io/UnsupportedEncodingException": ktfThrowableSubclassSpec(
		"java/io/IOException",
	),
	"java/io/Reader": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "close", descriptor: "()V"},
			{name: "mark", descriptor: "(I)V"},
			{name: "markSupported", descriptor: "()Z"},
			{name: "read", descriptor: "()I"},
			{name: "read", descriptor: "([C)I"},
			{name: "read", descriptor: "([CII)I"},
			{name: "ready", descriptor: "()Z"},
			{name: "reset", descriptor: "()V"},
			{name: "skip", descriptor: "(J)J"},
		},
	},
	"java/io/Writer": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "close", descriptor: "()V"},
			{name: "flush", descriptor: "()V"},
			{name: "write", descriptor: "(I)V"},
			{name: "write", descriptor: "([C)V"},
			{name: "write", descriptor: "([CII)V"},
			{name: "write", descriptor: "(Ljava/lang/String;)V"},
			{name: "write", descriptor: "(Ljava/lang/String;II)V"},
		},
	},
	"java/io/DataInput": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "readBoolean", descriptor: "()Z", access: 0x0401},
			{name: "readByte", descriptor: "()B", access: 0x0401},
			{name: "readUnsignedByte", descriptor: "()I", access: 0x0401},
			{name: "readShort", descriptor: "()S", access: 0x0401},
			{name: "readUnsignedShort", descriptor: "()I", access: 0x0401},
			{name: "readChar", descriptor: "()C", access: 0x0401},
			{name: "readInt", descriptor: "()I", access: 0x0401},
			{name: "readLong", descriptor: "()J", access: 0x0401},
			{name: "readFloat", descriptor: "()F", access: 0x0401},
			{name: "readDouble", descriptor: "()D", access: 0x0401},
			{name: "readFully", descriptor: "([B)V", access: 0x0401},
			{name: "readFully", descriptor: "([BII)V", access: 0x0401},
			{name: "readUTF", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "skipBytes", descriptor: "(I)I", access: 0x0401},
		},
	},
	"java/io/DataOutput": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "write", descriptor: "(I)V", access: 0x0401},
			{name: "write", descriptor: "([B)V", access: 0x0401},
			{name: "write", descriptor: "([BII)V", access: 0x0401},
			{name: "writeBoolean", descriptor: "(Z)V", access: 0x0401},
			{name: "writeByte", descriptor: "(I)V", access: 0x0401},
			{name: "writeShort", descriptor: "(I)V", access: 0x0401},
			{name: "writeChar", descriptor: "(I)V", access: 0x0401},
			{name: "writeInt", descriptor: "(I)V", access: 0x0401},
			{name: "writeLong", descriptor: "(J)V", access: 0x0401},
			{name: "writeFloat", descriptor: "(F)V", access: 0x0401},
			{name: "writeDouble", descriptor: "(D)V", access: 0x0401},
			{name: "writeChars", descriptor: "(Ljava/lang/String;)V", access: 0x0401},
			{name: "writeUTF", descriptor: "(Ljava/lang/String;)V", access: 0x0401},
		},
	},
	"java/io/OutputStreamWriter": {
		Parent:    "java/io/Writer",
		fieldSize: 4,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/io/OutputStream;)V"},
			{
				name:       "<init>",
				descriptor: "(Ljava/io/OutputStream;Ljava/lang/String;)V",
			},
			{name: "close", descriptor: "()V"},
			{name: "flush", descriptor: "()V"},
			{name: "write", descriptor: "(C)V"},
			{name: "write", descriptor: "(I)V"},
			{name: "write", descriptor: "([C)V"},
			{name: "write", descriptor: "([CII)V"},
			{name: "write", descriptor: "(Ljava/lang/String;)V"},
			{name: "write", descriptor: "(Ljava/lang/String;II)V"},
		},
	},

	"java/util/EmptyStackException": {
		Parent: "java/lang/RuntimeException",
	},
	"java/util/NoSuchElementException": {
		Parent: "java/lang/RuntimeException",
	},
	"java/util/SimpleTimeZone": {
		Parent: "java/util/TimeZone",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(ILjava/lang/String;)V"},
			{name: "<init>", descriptor: "(ILjava/lang/String;IIIIIIII)V"},
			{name: "equals", descriptor: "(Ljava/lang/Object;)Z"},
			{name: "getOffset", descriptor: "(IIIIII)I"},
			{name: "getRawOffset", descriptor: "()I"},
			{name: "hashCode", descriptor: "()I"},
			{name: "inDaylightTime", descriptor: "(Ljava/util/Date;)Z"},
			{name: "setRawOffset", descriptor: "(I)V"},
			{name: "setStartYear", descriptor: "(I)V"},
			{name: "useDaylightTime", descriptor: "()Z"},
		},
	},

	"org/kwis/msf/core/Kernel": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "execute", descriptor: "(Ljava/lang/String;[Ljava/lang/String;)I", access: 0x0008},
			{name: "mExecute", descriptor: "(Ljava/lang/String;[Ljava/lang/String;)I", access: 0x0008},
			{name: "load", descriptor: "(Ljava/lang/String;[Ljava/lang/String;)I", access: 0x0008},
			{name: "mLoad", descriptor: "(Ljava/lang/String;[Ljava/lang/String;)I", access: 0x0008},
			{name: "getExecNames", descriptor: "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;", access: 0x0008},
			{name: "getPrgID", descriptor: "()I", access: 0x0008},
			{name: "getAMID", descriptor: "()I", access: 0x0008},
			{name: "getParentPrgID", descriptor: "()I", access: 0x0008},
			{name: "getPrgInfo", descriptor: "()[I", access: 0x0008},
			{name: "stop", descriptor: "(I)V", access: 0x0008},
			{name: "letThrowExceptionWhenProgramExit", descriptor: "()I", access: 0x0008},
			{name: "getAccessLevel", descriptor: "()I", access: 0x0008},
			{name: "getPrgName", descriptor: "()Ljava/lang/String;", access: 0x0008},
		},
	},
	"org/kwis/msf/core/Shared": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "initialize", descriptor: "()V", access: 0x0008},
			{name: "createBuf", descriptor: "(Ljava/lang/String;I)[B", access: 0x0008},
			{name: "getBuf", descriptor: "(Ljava/lang/String;)[B", access: 0x0008},
			{name: "resizeBuf", descriptor: "([BI)[B", access: 0x0008},
			{name: "destroyBuf", descriptor: "([B)V", access: 0x0008},
			{name: "createBuf", descriptor: "(I)[B", access: 0x0008},
			{name: "getBuf", descriptor: "()[B", access: 0x0008},
			{name: "resizeBuf", descriptor: "(I)[B", access: 0x0008},
		},
	},
	"org/kwis/msf/core/ProgramExitException": {
		Parent:  "java/lang/RuntimeException",
		methods: ktfThrowableSubclassSpec("java/lang/RuntimeException").methods,
	},
	// Socket declares its methods so that a virtual call on one resolves to
	// Socket. Left empty, the host virtual slots are handed out globally and a
	// guest calling Socket.getInputStream() lands on whatever unrelated class
	// happens to own that slot - 마스터오브소드2 reached
	// org/kwis/msp/lwc/ProgressComponent.getInputStream() that way (#147).
	"org/kwis/msf/io/Socket": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "getInputStream", descriptor: "()Ljava/io/InputStream;", access: 0x0401},
			{name: "getOutputStream", descriptor: "()Ljava/io/OutputStream;", access: 0x0401},
			{name: "isStream", descriptor: "()Z", access: 0x0401},
			{name: "getMessageCount", descriptor: "()I", access: 0x0401},
			{name: "getMessageMaxLength", descriptor: "()I", access: 0x0401},
			{name: "send", descriptor: "(Lorg/kwis/msf/io/Message;)V", access: 0x0401},
			{name: "recv", descriptor: "(Lorg/kwis/msf/io/Message;)V", access: 0x0401},
			{name: "close", descriptor: "()V", access: 0x0401},
			{name: "accept", descriptor: "()Lorg/kwis/msf/io/Socket;", access: 0x0401},
		},
	},
	"org/kwis/msf/io/HttpSocket": {
		Parent: "org/kwis/msf/io/Socket",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "close", descriptor: "()V", access: 0x0401},
			{name: "getDate", descriptor: "()J", access: 0x0401},
			{name: "getEncoding", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "getExpiration", descriptor: "()J", access: 0x0401},
			{name: "getFile", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "getHeaderField", descriptor: "(Ljava/lang/String;)Ljava/lang/String;", access: 0x0401},
			{name: "getHost", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "getInputStream", descriptor: "()Ljava/io/InputStream;", access: 0x0401},
			{name: "getLastModified", descriptor: "()J", access: 0x0401},
			{name: "getLength", descriptor: "()J", access: 0x0401},
			{name: "getOutputStream", descriptor: "()Ljava/io/OutputStream;", access: 0x0401},
			{name: "getPort", descriptor: "()I", access: 0x0401},
			{name: "getProtocol", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "getQuery", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "getRef", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "getRequestMethod", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "getRequestProperty", descriptor: "(Ljava/lang/String;)Ljava/lang/String;", access: 0x0401},
			{name: "getResponseCode", descriptor: "()I", access: 0x0401},
			{name: "getResponseMessage", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "getType", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "getURL", descriptor: "()Ljava/lang/String;", access: 0x0401},
			{name: "isRelocatable", descriptor: "()Z", access: 0x0401},
			{name: "relocation", descriptor: "()Lorg/kwis/msf/io/HttpSocket;", access: 0x0401},
			{name: "setProxy", descriptor: "(Ljava/lang/String;I)V", access: 0x0401},
			{name: "setRequestMethod", descriptor: "(Ljava/lang/String;)V", access: 0x0401},
			{name: "setRequestProperty", descriptor: "(Ljava/lang/String;Ljava/lang/String;)V", access: 0x0401},
		},
	},
	"org/kwis/msf/io/Message": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "([B)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;[B)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;[BII)V"},
			{name: "getIndex", descriptor: "()B"},
			{name: "setIndex", descriptor: "(B)V"},
			{name: "getTeleServiceID", descriptor: "()I"},
			{name: "setTeleServiceID", descriptor: "(I)V"},
			{name: "getClassification", descriptor: "()B"},
			{name: "setClassification", descriptor: "(B)V"},
			{name: "getData", descriptor: "()[B"},
			{name: "getLength", descriptor: "()I"},
			{name: "setLength", descriptor: "(I)I"},
			{name: "getOffset", descriptor: "()I"},
			{name: "setOffset", descriptor: "(I)I"},
			{name: "getAddress", descriptor: "()Ljava/lang/String;"},
			{name: "setAddress", descriptor: "(Ljava/lang/String;)V"},
			{name: "getAddressInt", descriptor: "()I"},
			{name: "setAddressInt", descriptor: "(I)V"},
			{name: "getDate", descriptor: "()Ljava/util/Date;"},
			{name: "setDate", descriptor: "(Ljava/util/Date;)V"},
		},
	},
	"org/kwis/msf/io/URL": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "find", descriptor: "(Ljava/lang/String;)Lorg/kwis/msf/io/Socket;", access: 0x0008},
		},
	},
	"org/kwis/msf/io/SchemeNotFoundException": {
		Parent:  "java/io/IOException",
		methods: ktfThrowableSubclassSpec("java/io/IOException").methods,
	},

	"org/kwis/msp/db/DataBaseException": {
		Parent:  "java/lang/Exception",
		methods: ktfThrowableSubclassSpec("java/lang/Exception").methods,
	},
	"org/kwis/msp/db/DataBaseRecordException": {
		Parent:  "org/kwis/msp/db/DataBaseException",
		methods: ktfThrowableSubclassSpec("org/kwis/msp/db/DataBaseException").methods,
	},
	"org/kwis/msp/db/DataComparator": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "compare", descriptor: "([B[B)I", access: 0x0401},
		},
	},
	"org/kwis/msp/db/DataComparatorInteger": {
		Parent: "org/kwis/msp/db/DataComparator",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(I)V"},
			{name: "compare", descriptor: "([B[B)I"},
		},
	},
	"org/kwis/msp/db/DataComparatorString": {
		Parent: "org/kwis/msp/db/DataComparator",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(I)V"},
			{name: "compare", descriptor: "([B[B)I"},
		},
	},
	"org/kwis/msp/db/DataFilter": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "filter", descriptor: "([B)Z", access: 0x0401},
		},
	},
	"org/kwis/msp/db/DataFilterInteger": {
		Parent: "org/kwis/msp/db/DataFilter",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(III)V"},
			{name: "filter", descriptor: "([B)Z"},
		},
	},

	"org/kwis/msp/handset/Call": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "securePPPSession", descriptor: "()V", access: 0x0009},
			{name: "accept", descriptor: "()V", access: 0x0009},
			{name: "reject", descriptor: "()V", access: 0x0009},
			{name: "end", descriptor: "()V", access: 0x0009},
			{name: "place", descriptor: "(Ljava/lang/String;)V", access: 0x0009},
			{name: "securePPPSession0", descriptor: "()V", access: 0x000c},
			{name: "accept0", descriptor: "()V", access: 0x000c},
			{name: "reject0", descriptor: "()V", access: 0x000c},
			{name: "end0", descriptor: "()V", access: 0x000c},
			{name: "place0", descriptor: "(Ljava/lang/String;)V", access: 0x000c},
		},
	},
	"org/kwis/msp/handset/HandsetProperty": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "getSystemProperty", descriptor: "(Ljava/lang/String;)Ljava/lang/String;", access: 0x0008},
			{name: "setSystemProperty", descriptor: "(Ljava/lang/String;Ljava/lang/String;)Z", access: 0x0008},
		},
	},
	"org/kwis/msp/io/File": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;I)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;II)V"},
			{name: "openInputStream", descriptor: "()Ljava/io/InputStream;"},
			{name: "openDataInputStream", descriptor: "()Ljava/io/DataInputStream;"},
			{name: "openOutputStream", descriptor: "()Ljava/io/OutputStream;"},
			{name: "openDataOutputStream", descriptor: "()Ljava/io/DataOutputStream;"},
			{name: "close", descriptor: "()V"},
			{name: "write", descriptor: "(I)I"},
			{name: "write", descriptor: "([B)I"},
			{name: "write", descriptor: "([BII)I"},
			{name: "read", descriptor: "([B)I"},
			{name: "read", descriptor: "([BII)I"},
			{name: "seek", descriptor: "(I)V"},
			{name: "sizeOf", descriptor: "()I"},
		},
	},
	"org/kwis/msp/io/FileSystem": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "exists", descriptor: "(Ljava/lang/String;)Z", access: 0x0008},
		},
	},

	"org/kwis/msp/lcdui/DisplayProxy": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "isColor", descriptor: "()Z"},
			{name: "numColors", descriptor: "()I"},
			{name: "getBitsPerPixel", descriptor: "()I"},
			{name: "hasPointerEvents", descriptor: "()Z"},
			{name: "hasPointerMotionEvents", descriptor: "()Z"},
			{name: "hasRepeatEvents", descriptor: "()Z"},
			{name: "getWidth", descriptor: "()I"},
			{name: "getHeight", descriptor: "()I"},
			{name: "isDoubleBuffered", descriptor: "()Z"},
			{name: "flush", descriptor: "()V"},
			{name: "flush", descriptor: "(IIII)V"},
		},
	},
	"org/kwis/msp/lcdui/EventQueue": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "getNextEvent", descriptor: "([I)V"},
			{name: "dispatchEvent", descriptor: "([I)V"},
			{name: "postEvent", descriptor: "([I)Z"},
			{name: "postEvent", descriptor: "(I[I)V", access: 0x0008},
			{
				name:       "hookEvent",
				descriptor: "(ILorg/kwis/msp/lcdui/JletEventListener;)V",
				access:     0x0008,
			},
		},
	},
	"org/kwis/msp/lcdui/ImageObserver": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "notify", descriptor: "(Lorg/kwis/msp/lcdui/Image;I)V", access: 0x0401},
		},
	},
	"org/kwis/msp/lcdui/InputMethodHandler": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(I)V"},
			{name: "getCurrentModeCode", descriptor: "()Ljava/lang/String;"},
			{name: "notifyKeyInput", descriptor: "(II)Z"},
			{name: "getCurrentInputMode", descriptor: "()I"},
			{
				name:       "setInputMethodListener",
				descriptor: "(Lorg/kwis/msp/lcdui/InputMethodListener;)V",
			},
			{name: "changeCurrentModeToNext", descriptor: "()V"},
			{name: "getCurrentMode", descriptor: "()I"},
			{name: "setCurrentMode", descriptor: "(I)Z"},
			{name: "hideSymbolCard", descriptor: "()V"},
			{name: "setSymbolPosition", descriptor: "(IIII)V"},
		},
	},
	"org/kwis/msp/lcdui/InputMethodListener": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "notifyTextChanged", descriptor: "([CII)V", access: 0x0401},
		},
	},
	"org/kwis/msp/lcdui/JletEventListener": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "notifyEvent", descriptor: "(III)V", access: 0x0401},
		},
	},
	"org/kwis/msp/lcdui/JletStateChangeException": {
		Parent:  "java/lang/Exception",
		methods: ktfThrowableSubclassSpec("java/lang/Exception").methods,
	},
	"org/kwis/msp/lcdui/Main": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "main", descriptor: "([Ljava/lang/String;)V", access: 0x0008},
		},
	},
	"org/kwis/msp/lcdui/SystemEventListener": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "notifySystemEvent", descriptor: "(IIII)V", access: 0x0401},
		},
	},

	"org/kwis/msp/lwc/ActionListener": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "action", descriptor: "(Lorg/kwis/msp/lwc/Component;Ljava/lang/Object;)V", access: 0x0401},
		},
	},
	"org/kwis/msp/lwc/ChangeListener": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "changed", descriptor: "(Lorg/kwis/msp/lwc/Component;Ljava/lang/Object;)V", access: 0x0401},
		},
	},
	"org/kwis/msp/lwc/CommandListener": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{name: "commandAction", descriptor: "(Lorg/kwis/msp/lwc/Command;ILjava/lang/Object;)V", access: 0x0401},
		},
	},
	"org/kwis/msp/lwc/EventListener": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "eventNotify",
				descriptor: "(IIIILjava/lang/Object;)Z",
				access:     0x0401,
			},
		},
	},
	"org/kwis/msp/lwc/GrabKeyListener": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "grabKeyNotify",
				descriptor: "(IILjava/lang/Object;)Z",
				access:     0x0401,
			},
		},
	},
	"org/kwis/msp/lwc/ButtonComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Lorg/kwis/msp/lcdui/Image;)V"},
			{name: "calcPreferredSize", descriptor: "(I)V", access: 0x0004},
			{name: "getFont", descriptor: "()Lorg/kwis/msp/lcdui/Font;"},
			{name: "getImage", descriptor: "()Lorg/kwis/msp/lcdui/Image;"},
			{name: "getString", descriptor: "()Ljava/lang/String;"},
			{name: "keyNotify", descriptor: "(II)Z"},
			{name: "layout", descriptor: "()V", access: 0x0004},
			{name: "paintContent", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "setActionListener", descriptor: "(Lorg/kwis/msp/lwc/ActionListener;Ljava/lang/Object;)V"},
			{name: "setFont", descriptor: "(Lorg/kwis/msp/lcdui/Font;)V"},
			{name: "setImage", descriptor: "(Lorg/kwis/msp/lcdui/Image;)V"},
			{name: "setString", descriptor: "(Ljava/lang/String;)V"},
		},
	},
	"org/kwis/msp/lwc/CheckboxComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;Lorg/kwis/msp/lcdui/Image;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Lorg/kwis/msp/lcdui/Image;Lorg/kwis/msp/lwc/CheckboxGroup;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Lorg/kwis/msp/lcdui/Image;Z)V"},
			{name: "getState", descriptor: "()Z"},
			{name: "keyNotify", descriptor: "(II)Z"},
			{name: "paintContent", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "setChangeListener", descriptor: "(Lorg/kwis/msp/lwc/ChangeListener;Ljava/lang/Object;)V"},
			{name: "setState", descriptor: "(Z)V"},
		},
	},
	"org/kwis/msp/lwc/CheckboxGroup": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "select", descriptor: "(Lorg/kwis/msp/lwc/CheckboxComponent;)V"},
			{name: "getSelectedCheckbox", descriptor: "()Lorg/kwis/msp/lwc/CheckboxComponent;"},
			{name: "setChangeListener", descriptor: "(Lorg/kwis/msp/lwc/ChangeListener;Ljava/lang/Object;)V"},
		},
	},
	"org/kwis/msp/lwc/ComboComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "append", descriptor: "(Ljava/lang/String;)I"},
			{name: "delete", descriptor: "(I)V"},
			{name: "getPreferredHeight", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "(I)I"},
			{name: "getPreferredWidth", descriptor: "()I"},
			{name: "getSelectedIndex", descriptor: "()I"},
			{name: "getSize", descriptor: "()I"},
			{name: "getString", descriptor: "()Ljava/lang/String;"},
			{name: "insert", descriptor: "(ILjava/lang/String;)I"},
			{name: "keyNotify", descriptor: "(II)Z", access: 0x0004},
			{name: "paintContent", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "select", descriptor: "(I)V"},
			{name: "set", descriptor: "(ILjava/lang/String;)V"},
			{name: "setChangeListener", descriptor: "(Lorg/kwis/msp/lwc/ChangeListener;Ljava/lang/Object;)V"},
		},
	},
	"org/kwis/msp/lwc/Command": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;Ljava/lang/Object;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Lorg/kwis/msp/lcdui/Image;Ljava/lang/Object;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Lorg/kwis/msp/lcdui/Image;Lorg/kwis/msp/lcdui/Image;Ljava/lang/Object;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V"},
			{name: "getString", descriptor: "()Ljava/lang/String;"},
			{name: "getExtObject", descriptor: "()Ljava/lang/Object;"},
			{name: "getNormalImage", descriptor: "()Lorg/kwis/msp/lcdui/Image;"},
			{name: "getActiveImage", descriptor: "()Lorg/kwis/msp/lcdui/Image;"},
		},
	},
	"org/kwis/msp/lwc/CommandBarComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "addCommand", descriptor: "(Lorg/kwis/msp/lwc/Command;)I"},
			{name: "getActiveIndex", descriptor: "()I"},
			{name: "getCommand", descriptor: "(I)Lorg/kwis/msp/lwc/Command;"},
			{name: "getPreferredHeight", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "(I)I"},
			{name: "getPreferredWidth", descriptor: "()I"},
			{name: "getSize", descriptor: "()I"},
			{name: "keyNotify", descriptor: "(II)Z", access: 0x0004},
			{name: "paintContent", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "pointerNotify", descriptor: "(III)Z", access: 0x0004},
			{name: "removeAll", descriptor: "()V"},
			{name: "removeCommand", descriptor: "(Lorg/kwis/msp/lwc/Command;)V"},
			{name: "setActiveIndex", descriptor: "(I)V"},
			{name: "setCommandListener", descriptor: "(Lorg/kwis/msp/lwc/CommandListener;Ljava/lang/Object;)V"},
		},
	},
	"org/kwis/msp/lwc/DateFieldComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(I)V"},
			{name: "getDate", descriptor: "()Ljava/util/Date;"},
			{name: "getMode", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "(I)I"},
			{name: "getPreferredWidth", descriptor: "()I"},
			{name: "getStringValue", descriptor: "(I)Ljava/lang/String;"},
			{name: "getTimeZone", descriptor: "()Ljava/util/TimeZone;"},
			{name: "keyNotify", descriptor: "(II)Z"},
			{name: "paintContent", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "setDate", descriptor: "(Ljava/util/Date;)V"},
			{name: "setMode", descriptor: "(I)V"},
			{name: "setTimeZone", descriptor: "(Ljava/util/TimeZone;)V"},
			{name: "showNotify", descriptor: "(Z)V", access: 0x0004},
		},
	},
	"org/kwis/msp/lwc/Decorator": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "getColor", descriptor: "(I)I", access: 0x0008},
			{name: "getDarkShadowColor", descriptor: "(I)I", access: 0x0008},
			{name: "getShadowColor", descriptor: "(I)I", access: 0x0008},
			{name: "getLightColor", descriptor: "(I)I", access: 0x0008},
			{name: "getHighLightColor", descriptor: "(I)I", access: 0x0008},
		},
	},
	"org/kwis/msp/lwc/ImageComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(Lorg/kwis/msp/lcdui/Image;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
			{name: "getImage", descriptor: "()Lorg/kwis/msp/lcdui/Image;"},
			{name: "getPreferredHeight", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "(I)I"},
			{name: "getPreferredWidth", descriptor: "()I"},
			{name: "paintContent", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "play", descriptor: "()V"},
			{name: "setImage", descriptor: "(Lorg/kwis/msp/lcdui/Image;)V"},
			{name: "setImage", descriptor: "(Ljava/lang/String;)V"},
			{name: "setLayout", descriptor: "(I)V"},
			{name: "showNotify", descriptor: "(Z)V", access: 0x0004},
			{name: "stop", descriptor: "()V"},
		},
	},
	"org/kwis/msp/lwc/ListComponent": {
		Parent:              "org/kwis/msp/lwc/FormComponent",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(I)V"},
			{name: "addComponent", descriptor: "(Lorg/kwis/msp/lwc/Component;)I"},
			{name: "addComponent", descriptor: "(ILorg/kwis/msp/lwc/Component;)V"},
			{name: "append", descriptor: "(Ljava/lang/String;Lorg/kwis/msp/lcdui/Image;)I"},
			{name: "controlNumber", descriptor: "(Z)V"},
			{name: "delete", descriptor: "(I)V"},
			{name: "getImage", descriptor: "(I)Lorg/kwis/msp/lcdui/Image;"},
			{name: "getSelectedIndex", descriptor: "()I"},
			{name: "getSize", descriptor: "()I"},
			{name: "getString", descriptor: "()Ljava/lang/String;"},
			{name: "insert", descriptor: "(ILjava/lang/String;)I"},
			{name: "select", descriptor: "(I)V"},
			{name: "set", descriptor: "(ILjava/lang/String;)V"},
			{name: "setActionListener", descriptor: "(Lorg/kwis/msp/lwc/ActionListener;Ljava/lang/Object;)V"},
			{name: "setChangeListener", descriptor: "(Lorg/kwis/msp/lwc/ChangeListener;Ljava/lang/Object;)V"},
		},
	},
	"org/kwis/msp/lwc/ListItemComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Lorg/kwis/msp/lcdui/Image;)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;Ljava/lang/String;)V"},
			{name: "getState", descriptor: "()Z"},
			{name: "setState", descriptor: "(Z)V"},
		},
	},
	"org/kwis/msp/lwc/ProxyCard": {
		Parent:              "org/kwis/msp/lcdui/Card",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Lorg/kwis/msp/lwc/ContainerComponent;)V"},
			{name: "<init>", descriptor: "(Lorg/kwis/msp/lwc/ContainerComponent;Z)V"},
			{name: "<init>", descriptor: "(Lorg/kwis/msp/lwc/ContainerComponent;IIII)V"},
			{name: "<init>", descriptor: "(Lorg/kwis/msp/lwc/ContainerComponent;IIIIZ)V"},
			{name: "keyNotify", descriptor: "(II)Z", access: 0x0004},
			{name: "paint", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V", access: 0x0004},
			{name: "pointerNotify", descriptor: "(III)Z", access: 0x0004},
			{name: "showNotify", descriptor: "(Z)V", access: 0x0004},
		},
	},
	"org/kwis/msp/lwc/ScrollbarComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "()V"},
			{name: "<init>", descriptor: "(I)V"},
			{name: "<init>", descriptor: "(IIIIII)V"},
			{name: "focusNotify", descriptor: "(Z)V"},
			{name: "getChangeAmount", descriptor: "()I"},
			{name: "getCurrentValue", descriptor: "()I"},
			{name: "getDirection", descriptor: "()I"},
			{name: "getForegroundColor", descriptor: "()I"},
			{name: "getMaximum", descriptor: "()I"},
			{name: "getMinimum", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "(I)I"},
			{name: "getPreferredWidth", descriptor: "()I"},
			{name: "getViewAmount", descriptor: "()I"},
			{name: "keyNotify", descriptor: "(II)Z"},
			{name: "paintContent", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "setChangeAmount", descriptor: "(I)V"},
			{name: "setCurrentValue", descriptor: "(I)V"},
			{name: "setDirection", descriptor: "(I)V"},
			{name: "setForegroundColor", descriptor: "(I)V"},
			{name: "setMaximum", descriptor: "(I)V"},
			{name: "setMinimum", descriptor: "(I)V"},
			{name: "setViewAmount", descriptor: "(I)V"},
		},
	},
	"org/kwis/msp/lwc/TextBoxComponent": {
		Parent:              "org/kwis/msp/lwc/TextComponent",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;I)V"},
			{name: "<init>", descriptor: "(Ljava/lang/String;II)V"},
			{name: "configure", descriptor: "(IIIII)V"},
			{name: "delete", descriptor: "(II)V"},
			{name: "focusNotify", descriptor: "(Z)V"},
			{name: "getPreferredHeight", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "(I)I"},
			{name: "getPreferredWidth", descriptor: "()I"},
			{name: "insert", descriptor: "([CIII)V"},
			{name: "keyNotify", descriptor: "(II)Z"},
			{name: "paintContent", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "setFont", descriptor: "(Lorg/kwis/msp/lcdui/Font;)V"},
			{name: "setMaxLength", descriptor: "(I)V"},
			{name: "setString", descriptor: "(Ljava/lang/String;)V"},
		},
	},
	"org/kwis/msp/lwc/TextComponent$ModeViewer": {
		Parent: "java/lang/Object",
	},
	"org/kwis/msp/lwc/TickerComponent": {
		Parent:              "org/kwis/msp/lwc/Component",
		compatibilityVTable: true,
		methods: []ktfHostJavaMethodSpec{
			{name: "<init>", descriptor: "(Ljava/lang/String;Lorg/kwis/msp/lcdui/Image;)V"},
			{name: "getImage", descriptor: "()Lorg/kwis/msp/lcdui/Image;"},
			{name: "getPreferredHeight", descriptor: "()I"},
			{name: "getPreferredHeight", descriptor: "(I)I"},
			{name: "getPreferredWidth", descriptor: "()I"},
			{name: "getString", descriptor: "()Ljava/lang/String;"},
			{name: "paintContent", descriptor: "(Lorg/kwis/msp/lcdui/Graphics;)V"},
			{name: "setDelay", descriptor: "(I)V"},
			{name: "setImage", descriptor: "(Lorg/kwis/msp/lcdui/Image;)V"},
			{name: "setString", descriptor: "(Ljava/lang/String;)V"},
			{name: "setTickerState", descriptor: "(Z)Z"},
		},
	},

	"org/kwis/msp/media/MediaUnsupportedException": {
		Parent:  "java/lang/Exception",
		methods: ktfThrowableSubclassSpec("java/lang/Exception").methods,
	},
	"org/kwis/msp/media/PlayListener": {
		Parent: "java/lang/Object",
		access: 0x0601,
		methods: []ktfHostJavaMethodSpec{
			{
				name:       "playUpdate",
				descriptor: "(Lorg/kwis/msp/media/Clip;II)V",
				access:     0x0401,
			},
		},
	},
	"org/kwis/msp/media/Vibrator": {
		Parent: "java/lang/Object",
		methods: []ktfHostJavaMethodSpec{
			{name: "on", descriptor: "(II)V", access: 0x0009},
		},
	},
}
